// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module a0_xFSobelFilter3x3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        p_src_mat_V_V_dout,
        p_src_mat_V_V_empty_n,
        p_src_mat_V_V_read,
        p_gradx_mat_V_V_din,
        p_gradx_mat_V_V_full_n,
        p_gradx_mat_V_V_write,
        p_grady_mat_V_V_din,
        p_grady_mat_V_V_full_n,
        p_grady_mat_V_V_write,
        p_src_mat_rows_read_dout,
        p_src_mat_rows_read_empty_n,
        p_src_mat_rows_read_read,
        p_src_mat_cols_read_dout,
        p_src_mat_cols_read_empty_n,
        p_src_mat_cols_read_read
);

parameter    ap_ST_fsm_state1 = 8'd1;
parameter    ap_ST_fsm_pp0_stage0 = 8'd2;
parameter    ap_ST_fsm_state4 = 8'd4;
parameter    ap_ST_fsm_state5 = 8'd8;
parameter    ap_ST_fsm_pp1_stage0 = 8'd16;
parameter    ap_ST_fsm_state12 = 8'd32;
parameter    ap_ST_fsm_state13 = 8'd64;
parameter    ap_ST_fsm_state14 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [7:0] p_src_mat_V_V_dout;
input   p_src_mat_V_V_empty_n;
output   p_src_mat_V_V_read;
output  [7:0] p_gradx_mat_V_V_din;
input   p_gradx_mat_V_V_full_n;
output   p_gradx_mat_V_V_write;
output  [7:0] p_grady_mat_V_V_din;
input   p_grady_mat_V_V_full_n;
output   p_grady_mat_V_V_write;
input  [31:0] p_src_mat_rows_read_dout;
input   p_src_mat_rows_read_empty_n;
output   p_src_mat_rows_read_read;
input  [31:0] p_src_mat_cols_read_dout;
input   p_src_mat_cols_read_empty_n;
output   p_src_mat_cols_read_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg p_src_mat_V_V_read;
reg[7:0] p_gradx_mat_V_V_din;
reg p_gradx_mat_V_V_write;
reg[7:0] p_grady_mat_V_V_din;
reg p_grady_mat_V_V_write;
reg p_src_mat_rows_read_read;
reg p_src_mat_cols_read_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    p_src_mat_V_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] tmp_2_i_i_reg_717;
wire    ap_CS_fsm_pp1_stage0;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_pp1_stage0;
reg   [0:0] tmp_12_i_i_reg_776;
reg   [0:0] tmp_3_i_i_reg_768;
reg    p_gradx_mat_V_V_blk_n;
reg    ap_enable_reg_pp1_iter5;
reg   [0:0] tmp_15_i_i_reg_792;
reg   [0:0] tmp_15_i_i_reg_792_pp1_iter4_reg;
wire    ap_CS_fsm_state14;
reg    p_grady_mat_V_V_blk_n;
reg    p_src_mat_rows_read_blk_n;
reg    p_src_mat_cols_read_blk_n;
reg   [12:0] p_1_i_i_reg_244;
reg   [12:0] p_0177_0_i_i_i_reg_280;
reg   [7:0] src_buf3_V_0_i_i_reg_292;
reg   [7:0] src_buf2_0_V_reg_304;
reg   [7:0] src_buf2_V_0_i_i_reg_316;
reg   [7:0] src_buf3_0_V_reg_329;
reg   [7:0] src_buf1_0_V_reg_342;
reg   [7:0] src_buf1_V_0_i_i_reg_354;
wire   [15:0] tmp_1_fu_416_p1;
reg   [15:0] tmp_1_reg_705;
reg    ap_block_state1;
wire   [15:0] tmp_2_fu_420_p1;
reg   [15:0] tmp_2_reg_711;
wire   [0:0] tmp_2_i_i_fu_428_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_11001;
wire   [12:0] col_V_fu_433_p2;
reg   [12:0] col_V_reg_721;
reg    ap_enable_reg_pp0_iter0;
wire   [16:0] op2_assign_fu_448_p2;
reg   [16:0] op2_assign_reg_744;
wire    ap_CS_fsm_state4;
wire   [0:0] tmp_7_i_i_fu_458_p2;
wire    ap_CS_fsm_state5;
wire   [1:0] p_0455_3_i_i_fu_540_p3;
reg   [1:0] p_0455_3_i_i_reg_753;
wire   [1:0] p_0449_3_i_i_fu_556_p3;
reg   [1:0] p_0449_3_i_i_reg_758;
wire   [1:0] p_0443_3_i_i_fu_572_p3;
reg   [1:0] p_0443_3_i_i_reg_763;
wire   [0:0] tmp_3_i_i_fu_580_p2;
wire   [1:0] tmp_3_fu_585_p1;
reg   [1:0] tmp_3_reg_772;
wire   [0:0] tmp_12_i_i_fu_608_p2;
wire    ap_block_state6_pp1_stage0_iter0;
reg    ap_predicate_op105_read_state7;
reg    ap_block_state7_pp1_stage0_iter1;
wire    ap_block_state8_pp1_stage0_iter2;
wire    ap_block_state9_pp1_stage0_iter3;
wire    ap_block_state10_pp1_stage0_iter4;
reg    ap_block_state11_pp1_stage0_iter5;
reg    ap_block_pp1_stage0_11001;
reg   [0:0] tmp_12_i_i_reg_776_pp1_iter1_reg;
reg   [0:0] tmp_12_i_i_reg_776_pp1_iter2_reg;
reg   [0:0] tmp_12_i_i_reg_776_pp1_iter3_reg;
wire   [12:0] col_V_1_fu_613_p2;
reg   [12:0] col_V_1_reg_780;
reg    ap_enable_reg_pp1_iter0;
wire   [31:0] tmp_11_i_i_fu_619_p1;
reg   [31:0] tmp_11_i_i_reg_785;
wire   [0:0] tmp_15_i_i_fu_629_p2;
reg   [0:0] tmp_15_i_i_reg_792_pp1_iter2_reg;
reg   [0:0] tmp_15_i_i_reg_792_pp1_iter3_reg;
wire   [7:0] buf0_V_fu_635_p5;
reg   [7:0] buf0_V_reg_811;
reg    ap_enable_reg_pp1_iter3;
wire   [7:0] buf1_V_fu_647_p5;
reg   [7:0] buf1_V_reg_817;
wire   [7:0] buf2_V_fu_659_p5;
reg   [7:0] buf2_V_reg_823;
reg   [7:0] GradientValuesX_0_V_reg_829;
reg   [7:0] GradientValuesY_0_V_reg_834;
wire   [12:0] p_i_i_15_fu_691_p3;
reg   [12:0] p_i_i_15_reg_839;
wire    ap_CS_fsm_state12;
wire   [12:0] row_V_fu_699_p2;
reg   [12:0] row_V_reg_844;
wire   [7:0] grp_xFGradientX3x3_0_0_s_fu_384_ap_return;
reg   [7:0] GradientValuesX_0_V_2_reg_849;
wire    ap_CS_fsm_state13;
wire   [7:0] grp_xFGradientY3x3_0_0_s_fu_400_ap_return;
reg   [7:0] GradientValuesY_0_V_2_reg_854;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_block_pp1_stage0_subdone;
reg    ap_enable_reg_pp1_iter2;
reg    ap_enable_reg_pp1_iter4;
reg    ap_condition_pp1_exit_iter3_state9;
wire   [9:0] buf_0_V_address0;
reg    buf_0_V_ce0;
wire   [7:0] buf_0_V_q0;
reg   [9:0] buf_0_V_address1;
reg    buf_0_V_ce1;
reg    buf_0_V_we1;
reg   [7:0] buf_0_V_d1;
wire   [9:0] buf_1_V_address0;
reg    buf_1_V_ce0;
wire   [7:0] buf_1_V_q0;
reg   [9:0] buf_1_V_address1;
reg    buf_1_V_ce1;
reg    buf_1_V_we1;
reg   [7:0] buf_1_V_d1;
wire   [9:0] buf_2_V_address0;
reg    buf_2_V_ce0;
wire   [7:0] buf_2_V_q0;
reg   [9:0] buf_2_V_address1;
reg    buf_2_V_ce1;
reg    buf_2_V_we1;
reg   [7:0] buf_2_V_d1;
wire   [7:0] grp_xFSobel3x3_1_0_0_s_fu_367_ap_return_0;
wire   [7:0] grp_xFSobel3x3_1_0_0_s_fu_367_ap_return_1;
reg    grp_xFSobel3x3_1_0_0_s_fu_367_ap_ce;
reg    grp_xFGradientX3x3_0_0_s_fu_384_ap_ce;
reg    grp_xFGradientY3x3_0_0_s_fu_400_ap_ce;
reg   [12:0] ap_phi_mux_p_1_i_i_phi_fu_248_p4;
reg   [12:0] p_2_i_i_reg_256;
reg    ap_block_state14;
reg   [12:0] p_6_i_i_reg_268;
reg   [12:0] ap_phi_mux_p_0177_0_i_i_i_phi_fu_284_p4;
reg   [7:0] ap_phi_mux_src_buf3_V_0_i_i_phi_fu_296_p4;
reg   [7:0] ap_phi_mux_src_buf2_V_0_i_i_phi_fu_320_p4;
reg   [7:0] ap_phi_mux_src_buf3_0_V_phi_fu_334_p4;
reg   [7:0] ap_phi_mux_src_buf1_0_V_phi_fu_346_p4;
reg   [7:0] ap_phi_mux_src_buf1_V_0_i_i_phi_fu_358_p4;
wire   [31:0] tmp_1_i_i_fu_439_p1;
wire   [9:0] buf_0_V_addr_1_gep_fu_200_p3;
wire   [9:0] buf_1_V_addr_1_gep_fu_206_p3;
wire   [9:0] buf_2_V_addr_gep_fu_212_p3;
reg    ap_block_pp1_stage0_01001;
reg   [1:0] p_5_i_i_fu_96;
reg   [1:0] p_4_i_i_fu_100;
reg   [1:0] p_3_i_i_fu_104;
wire   [15:0] tmp_1_cast_i_i_fu_424_p1;
wire   [16:0] tmp_5_cast100_i_i_fu_445_p1;
wire   [16:0] tmp_6_cast_i_i_fu_454_p1;
wire   [0:0] tmp_i_i_fu_488_p2;
wire   [0:0] tmp_8_i_i_fu_476_p2;
wire   [0:0] tmp_9_i_i_fu_482_p2;
wire   [0:0] sel_tmp1_fu_518_p2;
wire   [0:0] sel_tmp2_fu_524_p2;
wire   [0:0] tmp_fu_534_p2;
wire   [1:0] sel_tmp_fu_530_p1;
wire   [1:0] p_i_i_fu_494_p3;
wire   [1:0] sel_tmp4_fu_548_p3;
wire   [1:0] p_1_i_i_12_fu_502_p3;
wire   [1:0] sel_tmp8_fu_564_p3;
wire   [1:0] p_2_i_i_13_fu_510_p3;
wire   [15:0] tmp_6_cast99_i_i_fu_472_p1;
wire   [15:0] tmp_11_cast_i_i_fu_604_p1;
wire   [12:0] row_ind_V_fu_679_p2;
wire   [0:0] tmp_14_i_i_fu_685_p2;
reg   [7:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_condition_675;
reg    ap_condition_679;
reg    ap_condition_368;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp1_iter4 = 1'b0;
end

a0_xFSobelFilter3x3_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
buf_0_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_0_V_address0),
    .ce0(buf_0_V_ce0),
    .q0(buf_0_V_q0),
    .address1(buf_0_V_address1),
    .ce1(buf_0_V_ce1),
    .we1(buf_0_V_we1),
    .d1(buf_0_V_d1)
);

a0_xFSobelFilter3x3_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
buf_1_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_1_V_address0),
    .ce0(buf_1_V_ce0),
    .q0(buf_1_V_q0),
    .address1(buf_1_V_address1),
    .ce1(buf_1_V_ce1),
    .we1(buf_1_V_we1),
    .d1(buf_1_V_d1)
);

a0_xFSobelFilter3x3_bkb #(
    .DataWidth( 8 ),
    .AddressRange( 640 ),
    .AddressWidth( 10 ))
buf_2_V_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(buf_2_V_address0),
    .ce0(buf_2_V_ce0),
    .q0(buf_2_V_q0),
    .address1(buf_2_V_address1),
    .ce1(buf_2_V_ce1),
    .we1(buf_2_V_we1),
    .d1(buf_2_V_d1)
);

a0_xFSobel3x3_1_0_0_s grp_xFSobel3x3_1_0_0_s_fu_367(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .src_buf1_0_V_read(ap_phi_mux_src_buf1_V_0_i_i_phi_fu_358_p4),
    .src_buf1_1_V_read(ap_phi_mux_src_buf1_0_V_phi_fu_346_p4),
    .src_buf1_2_V_read(buf0_V_fu_635_p5),
    .src_buf2_0_V_read(ap_phi_mux_src_buf2_V_0_i_i_phi_fu_320_p4),
    .src_buf2_2_V_read(buf1_V_fu_647_p5),
    .src_buf3_0_V_read(ap_phi_mux_src_buf3_V_0_i_i_phi_fu_296_p4),
    .src_buf3_1_V_read(ap_phi_mux_src_buf3_0_V_phi_fu_334_p4),
    .src_buf3_2_V_read(buf2_V_fu_659_p5),
    .ap_return_0(grp_xFSobel3x3_1_0_0_s_fu_367_ap_return_0),
    .ap_return_1(grp_xFSobel3x3_1_0_0_s_fu_367_ap_return_1),
    .ap_ce(grp_xFSobel3x3_1_0_0_s_fu_367_ap_ce)
);

a0_xFGradientX3x3_0_0_s grp_xFGradientX3x3_0_0_s_fu_384(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0_V(src_buf1_V_0_i_i_reg_354),
    .t2_V(8'd0),
    .m0_V(src_buf2_V_0_i_i_reg_316),
    .m2_V(8'd0),
    .b0_V(src_buf3_V_0_i_i_reg_292),
    .b2_V(8'd0),
    .ap_return(grp_xFGradientX3x3_0_0_s_fu_384_ap_return),
    .ap_ce(grp_xFGradientX3x3_0_0_s_fu_384_ap_ce)
);

a0_xFGradientY3x3_0_0_s grp_xFGradientY3x3_0_0_s_fu_400(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0_V(src_buf1_V_0_i_i_reg_354),
    .t1_V(src_buf1_0_V_reg_342),
    .t2_V(8'd0),
    .b0_V(src_buf3_V_0_i_i_reg_292),
    .b1_V(src_buf3_0_V_reg_329),
    .b2_V(8'd0),
    .ap_return(grp_xFGradientY3x3_0_0_s_fu_400_ap_return),
    .ap_ce(grp_xFGradientY3x3_0_0_s_fu_400_ap_ce)
);

a0_sobel_accel_mux_3eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_accel_mux_3eOg_U33(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(p_0455_3_i_i_reg_753),
    .dout(buf0_V_fu_635_p5)
);

a0_sobel_accel_mux_3eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_accel_mux_3eOg_U34(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(p_0449_3_i_i_reg_758),
    .dout(buf1_V_fu_647_p5)
);

a0_sobel_accel_mux_3eOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
sobel_accel_mux_3eOg_U35(
    .din0(buf_0_V_q0),
    .din1(buf_1_V_q0),
    .din2(buf_2_V_q0),
    .din3(p_0443_3_i_i_reg_763),
    .dout(buf2_V_fu_659_p5)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((tmp_7_i_i_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2))) begin
            ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((tmp_12_i_i_fu_608_p2 == 1'd0) & (1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp1_exit_iter3_state9)) begin
                ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter2;
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter4 <= ap_enable_reg_pp1_iter3;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp1_stage0_subdone)) begin
            ap_enable_reg_pp1_iter5 <= ap_enable_reg_pp1_iter4;
        end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
            ap_enable_reg_pp1_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        p_0177_0_i_i_i_reg_280 <= col_V_1_reg_780;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0177_0_i_i_i_reg_280 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_2_i_i_reg_717 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        p_1_i_i_reg_244 <= col_V_reg_721;
    end else if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_1_i_i_reg_244 <= 13'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
        p_2_i_i_reg_256 <= p_i_i_15_reg_839;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_2_i_i_reg_256 <= 13'd2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
        p_6_i_i_reg_268 <= row_V_reg_844;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        p_6_i_i_reg_268 <= 13'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf1_0_V_reg_342 <= buf0_V_reg_811;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        src_buf1_0_V_reg_342 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf1_V_0_i_i_reg_354 <= src_buf1_0_V_reg_342;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        src_buf1_V_0_i_i_reg_354 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf2_0_V_reg_304 <= buf1_V_reg_817;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        src_buf2_0_V_reg_304 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf2_V_0_i_i_reg_316 <= src_buf2_0_V_reg_304;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        src_buf2_V_0_i_i_reg_316 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf3_0_V_reg_329 <= buf2_V_reg_823;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        src_buf3_0_V_reg_329 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        src_buf3_V_0_i_i_reg_292 <= src_buf3_0_V_reg_329;
    end else if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        src_buf3_V_0_i_i_reg_292 <= 8'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        GradientValuesX_0_V_2_reg_849 <= grp_xFGradientX3x3_0_0_s_fu_384_ap_return;
        GradientValuesY_0_V_2_reg_854 <= grp_xFGradientY3x3_0_0_s_fu_400_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        GradientValuesX_0_V_reg_829 <= grp_xFSobel3x3_1_0_0_s_fu_367_ap_return_0;
        GradientValuesY_0_V_reg_834 <= grp_xFSobel3x3_1_0_0_s_fu_367_ap_return_1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776_pp1_iter2_reg == 1'd1) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        buf0_V_reg_811 <= buf0_V_fu_635_p5;
        buf1_V_reg_817 <= buf1_V_fu_647_p5;
        buf2_V_reg_823 <= buf2_V_fu_659_p5;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        col_V_1_reg_780 <= col_V_1_fu_613_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        col_V_reg_721 <= col_V_fu_433_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        op2_assign_reg_744 <= op2_assign_fu_448_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_7_i_i_fu_458_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        p_0443_3_i_i_reg_763 <= p_0443_3_i_i_fu_572_p3;
        p_0449_3_i_i_reg_758 <= p_0449_3_i_i_fu_556_p3;
        p_0455_3_i_i_reg_753 <= p_0455_3_i_i_fu_540_p3;
        p_3_i_i_fu_104 <= p_0455_3_i_i_fu_540_p3;
        p_4_i_i_fu_100 <= p_0449_3_i_i_fu_556_p3;
        p_5_i_i_fu_96 <= p_0443_3_i_i_fu_572_p3;
        tmp_3_i_i_reg_768 <= tmp_3_i_i_fu_580_p2;
        tmp_3_reg_772 <= tmp_3_fu_585_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        p_i_i_15_reg_839 <= p_i_i_15_fu_691_p3;
        row_V_reg_844 <= row_V_fu_699_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_12_i_i_reg_776 == 1'd1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_11_i_i_reg_785[12 : 0] <= tmp_11_i_i_fu_619_p1[12 : 0];
        tmp_15_i_i_reg_792 <= tmp_15_i_i_fu_629_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        tmp_12_i_i_reg_776 <= tmp_12_i_i_fu_608_p2;
        tmp_12_i_i_reg_776_pp1_iter1_reg <= tmp_12_i_i_reg_776;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp1_stage0_11001)) begin
        tmp_12_i_i_reg_776_pp1_iter2_reg <= tmp_12_i_i_reg_776_pp1_iter1_reg;
        tmp_12_i_i_reg_776_pp1_iter3_reg <= tmp_12_i_i_reg_776_pp1_iter2_reg;
        tmp_15_i_i_reg_792_pp1_iter2_reg <= tmp_15_i_i_reg_792;
        tmp_15_i_i_reg_792_pp1_iter3_reg <= tmp_15_i_i_reg_792_pp1_iter2_reg;
        tmp_15_i_i_reg_792_pp1_iter4_reg <= tmp_15_i_i_reg_792_pp1_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_1_reg_705 <= tmp_1_fu_416_p1;
        tmp_2_reg_711 <= tmp_2_fu_420_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_2_i_i_reg_717 <= tmp_2_i_i_fu_428_p2;
    end
end

always @ (*) begin
    if ((tmp_2_i_i_fu_428_p2 == 1'd0)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        ap_condition_pp1_exit_iter3_state9 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter3_state9 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_7_i_i_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter5 == 1'b0) & (ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_p_0177_0_i_i_i_phi_fu_284_p4 = col_V_1_reg_780;
    end else begin
        ap_phi_mux_p_0177_0_i_i_i_phi_fu_284_p4 = p_0177_0_i_i_i_reg_280;
    end
end

always @ (*) begin
    if (((tmp_2_i_i_reg_717 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_p_1_i_i_phi_fu_248_p4 = col_V_reg_721;
    end else begin
        ap_phi_mux_p_1_i_i_phi_fu_248_p4 = p_1_i_i_reg_244;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf1_0_V_phi_fu_346_p4 = buf0_V_reg_811;
    end else begin
        ap_phi_mux_src_buf1_0_V_phi_fu_346_p4 = src_buf1_0_V_reg_342;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf1_V_0_i_i_phi_fu_358_p4 = src_buf1_0_V_reg_342;
    end else begin
        ap_phi_mux_src_buf1_V_0_i_i_phi_fu_358_p4 = src_buf1_V_0_i_i_reg_354;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf2_V_0_i_i_phi_fu_320_p4 = src_buf2_0_V_reg_304;
    end else begin
        ap_phi_mux_src_buf2_V_0_i_i_phi_fu_320_p4 = src_buf2_V_0_i_i_reg_316;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf3_0_V_phi_fu_334_p4 = buf2_V_reg_823;
    end else begin
        ap_phi_mux_src_buf3_0_V_phi_fu_334_p4 = src_buf3_0_V_reg_329;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776_pp1_iter3_reg == 1'd1) & (ap_enable_reg_pp1_iter4 == 1'b1))) begin
        ap_phi_mux_src_buf3_V_0_i_i_phi_fu_296_p4 = src_buf3_0_V_reg_329;
    end else begin
        ap_phi_mux_src_buf3_V_0_i_i_phi_fu_296_p4 = src_buf3_V_0_i_i_reg_292;
    end
end

always @ (*) begin
    if (((tmp_7_i_i_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_3_reg_772 == 2'd0))) begin
        buf_0_V_address1 = buf_0_V_addr_1_gep_fu_200_p3;
    end else if (((tmp_3_i_i_reg_768 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (p_0443_3_i_i_reg_763 == 2'd0))) begin
        buf_0_V_address1 = tmp_11_i_i_fu_619_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_0_V_address1 = tmp_1_i_i_fu_439_p1;
    end else begin
        buf_0_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        buf_0_V_ce0 = 1'b1;
    end else begin
        buf_0_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_3_reg_772 == 2'd0)) | ((tmp_3_i_i_reg_768 == 1'd0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (p_0443_3_i_i_reg_763 == 2'd0)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_0_V_ce1 = 1'b1;
    end else begin
        buf_0_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_3_reg_772 == 2'd0))) begin
        buf_0_V_d1 = p_src_mat_V_V_dout;
    end else if ((((tmp_3_i_i_reg_768 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (p_0443_3_i_i_reg_763 == 2'd0)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_0_V_d1 = 8'd0;
    end else begin
        buf_0_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_3_reg_772 == 2'd0)) | ((tmp_3_i_i_reg_768 == 1'd0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (p_0443_3_i_i_reg_763 == 2'd0)) | ((tmp_2_i_i_reg_717 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_0_V_we1 = 1'b1;
    end else begin
        buf_0_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp1_stage0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_3_reg_772 == 2'd1))) begin
        buf_1_V_address1 = buf_1_V_addr_1_gep_fu_206_p3;
    end else if (((tmp_3_i_i_reg_768 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (p_0443_3_i_i_reg_763 == 2'd1))) begin
        buf_1_V_address1 = tmp_11_i_i_fu_619_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buf_1_V_address1 = tmp_1_i_i_fu_439_p1;
    end else begin
        buf_1_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        buf_1_V_ce0 = 1'b1;
    end else begin
        buf_1_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_3_reg_772 == 2'd1)) | ((tmp_3_i_i_reg_768 == 1'd0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (p_0443_3_i_i_reg_763 == 2'd1)) | ((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_1_V_ce1 = 1'b1;
    end else begin
        buf_1_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_3_i_i_reg_768 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (p_0443_3_i_i_reg_763 == 2'd1))) begin
        buf_1_V_d1 = 8'd0;
    end else if ((((1'b0 == ap_block_pp1_stage0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (tmp_3_reg_772 == 2'd1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        buf_1_V_d1 = p_src_mat_V_V_dout;
    end else begin
        buf_1_V_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (tmp_3_reg_772 == 2'd1)) | ((tmp_3_i_i_reg_768 == 1'd0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001) & (p_0443_3_i_i_reg_763 == 2'd1)) | ((tmp_2_i_i_reg_717 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        buf_1_V_we1 = 1'b1;
    end else begin
        buf_1_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_368)) begin
        if ((1'b1 == ap_condition_679)) begin
            buf_2_V_address1 = buf_2_V_addr_gep_fu_212_p3;
        end else if ((1'b1 == ap_condition_675)) begin
            buf_2_V_address1 = tmp_11_i_i_fu_619_p1;
        end else begin
            buf_2_V_address1 = 'bx;
        end
    end else begin
        buf_2_V_address1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter2 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        buf_2_V_ce0 = 1'b1;
    end else begin
        buf_2_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((~(tmp_3_reg_772 == 2'd1) & ~(tmp_3_reg_772 == 2'd0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | (~(p_0443_3_i_i_reg_763 == 2'd1) & ~(p_0443_3_i_i_reg_763 == 2'd0) & (tmp_3_i_i_reg_768 == 1'd0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buf_2_V_ce1 = 1'b1;
    end else begin
        buf_2_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_368)) begin
        if ((1'b1 == ap_condition_679)) begin
            buf_2_V_d1 = p_src_mat_V_V_dout;
        end else if ((1'b1 == ap_condition_675)) begin
            buf_2_V_d1 = 8'd0;
        end else begin
            buf_2_V_d1 = 'bx;
        end
    end else begin
        buf_2_V_d1 = 'bx;
    end
end

always @ (*) begin
    if (((~(tmp_3_reg_772 == 2'd1) & ~(tmp_3_reg_772 == 2'd0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | (~(p_0443_3_i_i_reg_763 == 2'd1) & ~(p_0443_3_i_i_reg_763 == 2'd0) & (tmp_3_i_i_reg_768 == 1'd0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        buf_2_V_we1 = 1'b1;
    end else begin
        buf_2_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_xFGradientX3x3_0_0_s_fu_384_ap_ce = 1'b1;
    end else begin
        grp_xFGradientX3x3_0_0_s_fu_384_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_xFGradientY3x3_0_0_s_fu_400_ap_ce = 1'b1;
    end else begin
        grp_xFGradientY3x3_0_0_s_fu_400_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        grp_xFSobel3x3_1_0_0_s_fu_367_ap_ce = 1'b1;
    end else begin
        grp_xFSobel3x3_1_0_0_s_fu_367_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1)))) begin
        p_gradx_mat_V_V_blk_n = p_gradx_mat_V_V_full_n;
    end else begin
        p_gradx_mat_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
        p_gradx_mat_V_V_din = GradientValuesX_0_V_2_reg_849;
    end else if (((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_01001) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        p_gradx_mat_V_V_din = GradientValuesX_0_V_reg_829;
    end else begin
        p_gradx_mat_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | (~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)))) begin
        p_gradx_mat_V_V_write = 1'b1;
    end else begin
        p_gradx_mat_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state14) | ((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter5 == 1'b1)))) begin
        p_grady_mat_V_V_blk_n = p_grady_mat_V_V_full_n;
    end else begin
        p_grady_mat_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
        p_grady_mat_V_V_din = GradientValuesY_0_V_2_reg_854;
    end else if (((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (1'b0 == ap_block_pp1_stage0_01001) & (ap_enable_reg_pp1_iter5 == 1'b1))) begin
        p_grady_mat_V_V_din = GradientValuesY_0_V_reg_834;
    end else begin
        p_grady_mat_V_V_din = 'bx;
    end
end

always @ (*) begin
    if ((((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (ap_enable_reg_pp1_iter5 == 1'b1) & (1'b0 == ap_block_pp1_stage0_11001)) | (~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14)))) begin
        p_grady_mat_V_V_write = 1'b1;
    end else begin
        p_grady_mat_V_V_write = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp1_stage0) & (tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0)) | ((tmp_2_i_i_reg_717 == 1'd1) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        p_src_mat_V_V_blk_n = p_src_mat_V_V_empty_n;
    end else begin
        p_src_mat_V_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((((ap_predicate_op105_read_state7 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_2_i_i_reg_717 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        p_src_mat_V_V_read = 1'b1;
    end else begin
        p_src_mat_V_V_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_cols_read_blk_n = p_src_mat_cols_read_empty_n;
    end else begin
        p_src_mat_cols_read_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_cols_read_read = 1'b1;
    end else begin
        p_src_mat_cols_read_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_rows_read_blk_n = p_src_mat_rows_read_empty_n;
    end else begin
        p_src_mat_rows_read_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        p_src_mat_rows_read_read = 1'b1;
    end else begin
        p_src_mat_rows_read_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if (~((tmp_2_i_i_fu_428_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if (((tmp_2_i_i_fu_428_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((tmp_7_i_i_fu_458_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1)) & ~((ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if ((((ap_enable_reg_pp1_iter4 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter5 == 1'b1)) | ((ap_enable_reg_pp1_iter4 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if ((~((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0)) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd3];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((tmp_2_i_i_reg_717 == 1'd1) & (p_src_mat_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((tmp_2_i_i_reg_717 == 1'd1) & (p_src_mat_V_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp1_stage0_01001 = (((ap_enable_reg_pp1_iter5 == 1'b1) & (((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_grady_mat_V_V_full_n == 1'b0)) | ((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_gradx_mat_V_V_full_n == 1'b0)))) | ((p_src_mat_V_V_empty_n == 1'b0) & (ap_predicate_op105_read_state7 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_11001 = (((ap_enable_reg_pp1_iter5 == 1'b1) & (((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_grady_mat_V_V_full_n == 1'b0)) | ((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_gradx_mat_V_V_full_n == 1'b0)))) | ((p_src_mat_V_V_empty_n == 1'b0) & (ap_predicate_op105_read_state7 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_pp1_stage0_subdone = (((ap_enable_reg_pp1_iter5 == 1'b1) & (((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_grady_mat_V_V_full_n == 1'b0)) | ((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_gradx_mat_V_V_full_n == 1'b0)))) | ((p_src_mat_V_V_empty_n == 1'b0) & (ap_predicate_op105_read_state7 == 1'b1) & (ap_enable_reg_pp1_iter1 == 1'b1)));
end

always @ (*) begin
    ap_block_state1 = ((p_src_mat_cols_read_empty_n == 1'b0) | (p_src_mat_rows_read_empty_n == 1'b0) | (ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state10_pp1_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state11_pp1_stage0_iter5 = (((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_grady_mat_V_V_full_n == 1'b0)) | ((tmp_15_i_i_reg_792_pp1_iter4_reg == 1'd0) & (p_gradx_mat_V_V_full_n == 1'b0)));
end

always @ (*) begin
    ap_block_state14 = ((p_grady_mat_V_V_full_n == 1'b0) | (p_gradx_mat_V_V_full_n == 1'b0));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((tmp_2_i_i_reg_717 == 1'd1) & (p_src_mat_V_V_empty_n == 1'b0));
end

assign ap_block_state6_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp1_stage0_iter1 = ((p_src_mat_V_V_empty_n == 1'b0) & (ap_predicate_op105_read_state7 == 1'b1));
end

assign ap_block_state8_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_368 = ((1'b0 == ap_block_pp1_stage0) & (tmp_12_i_i_reg_776 == 1'd1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0));
end

always @ (*) begin
    ap_condition_675 = (~(p_0443_3_i_i_reg_763 == 2'd1) & ~(p_0443_3_i_i_reg_763 == 2'd0) & (tmp_3_i_i_reg_768 == 1'd0));
end

always @ (*) begin
    ap_condition_679 = (~(tmp_3_reg_772 == 2'd1) & ~(tmp_3_reg_772 == 2'd0) & (tmp_3_i_i_reg_768 == 1'd1));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

always @ (*) begin
    ap_predicate_op105_read_state7 = ((tmp_3_i_i_reg_768 == 1'd1) & (tmp_12_i_i_reg_776 == 1'd1));
end

assign buf_0_V_addr_1_gep_fu_200_p3 = tmp_11_i_i_fu_619_p1;

assign buf_0_V_address0 = tmp_11_i_i_reg_785;

assign buf_1_V_addr_1_gep_fu_206_p3 = tmp_11_i_i_fu_619_p1;

assign buf_1_V_address0 = tmp_11_i_i_reg_785;

assign buf_2_V_addr_gep_fu_212_p3 = tmp_11_i_i_fu_619_p1;

assign buf_2_V_address0 = tmp_11_i_i_reg_785;

assign col_V_1_fu_613_p2 = (ap_phi_mux_p_0177_0_i_i_i_phi_fu_284_p4 + 13'd1);

assign col_V_fu_433_p2 = (ap_phi_mux_p_1_i_i_phi_fu_248_p4 + 13'd1);

assign op2_assign_fu_448_p2 = (tmp_5_cast100_i_i_fu_445_p1 + 17'd1);

assign p_0443_3_i_i_fu_572_p3 = ((tmp_fu_534_p2[0:0] === 1'b1) ? sel_tmp8_fu_564_p3 : p_2_i_i_13_fu_510_p3);

assign p_0449_3_i_i_fu_556_p3 = ((tmp_fu_534_p2[0:0] === 1'b1) ? sel_tmp4_fu_548_p3 : p_1_i_i_12_fu_502_p3);

assign p_0455_3_i_i_fu_540_p3 = ((tmp_fu_534_p2[0:0] === 1'b1) ? sel_tmp_fu_530_p1 : p_i_i_fu_494_p3);

assign p_1_i_i_12_fu_502_p3 = ((tmp_i_i_fu_488_p2[0:0] === 1'b1) ? 2'd0 : p_4_i_i_fu_100);

assign p_2_i_i_13_fu_510_p3 = ((tmp_i_i_fu_488_p2[0:0] === 1'b1) ? 2'd1 : p_5_i_i_fu_96);

assign p_i_i_15_fu_691_p3 = ((tmp_14_i_i_fu_685_p2[0:0] === 1'b1) ? 13'd0 : row_ind_V_fu_679_p2);

assign p_i_i_fu_494_p3 = ((tmp_i_i_fu_488_p2[0:0] === 1'b1) ? 2'd2 : p_3_i_i_fu_104);

assign row_V_fu_699_p2 = (p_6_i_i_reg_268 + 13'd1);

assign row_ind_V_fu_679_p2 = (p_2_i_i_reg_256 + 13'd1);

assign sel_tmp1_fu_518_p2 = (tmp_8_i_i_fu_476_p2 ^ 1'd1);

assign sel_tmp2_fu_524_p2 = (tmp_9_i_i_fu_482_p2 & sel_tmp1_fu_518_p2);

assign sel_tmp4_fu_548_p3 = ((sel_tmp2_fu_524_p2[0:0] === 1'b1) ? 2'd2 : 2'd1);

assign sel_tmp8_fu_564_p3 = ((sel_tmp2_fu_524_p2[0:0] === 1'b1) ? 2'd0 : 2'd2);

assign sel_tmp_fu_530_p1 = sel_tmp2_fu_524_p2;

assign tmp_11_cast_i_i_fu_604_p1 = ap_phi_mux_p_0177_0_i_i_i_phi_fu_284_p4;

assign tmp_11_i_i_fu_619_p1 = p_0177_0_i_i_i_reg_280;

assign tmp_12_i_i_fu_608_p2 = ((tmp_11_cast_i_i_fu_604_p1 < tmp_2_reg_711) ? 1'b1 : 1'b0);

assign tmp_14_i_i_fu_685_p2 = ((row_ind_V_fu_679_p2 == 13'd3) ? 1'b1 : 1'b0);

assign tmp_15_i_i_fu_629_p2 = ((p_0177_0_i_i_i_reg_280 == 13'd0) ? 1'b1 : 1'b0);

assign tmp_1_cast_i_i_fu_424_p1 = ap_phi_mux_p_1_i_i_phi_fu_248_p4;

assign tmp_1_fu_416_p1 = p_src_mat_rows_read_dout[15:0];

assign tmp_1_i_i_fu_439_p1 = p_1_i_i_reg_244;

assign tmp_2_fu_420_p1 = p_src_mat_cols_read_dout[15:0];

assign tmp_2_i_i_fu_428_p2 = ((tmp_1_cast_i_i_fu_424_p1 < tmp_2_reg_711) ? 1'b1 : 1'b0);

assign tmp_3_fu_585_p1 = p_2_i_i_reg_256[1:0];

assign tmp_3_i_i_fu_580_p2 = ((tmp_6_cast99_i_i_fu_472_p1 < tmp_1_reg_705) ? 1'b1 : 1'b0);

assign tmp_5_cast100_i_i_fu_445_p1 = tmp_1_reg_705;

assign tmp_6_cast99_i_i_fu_472_p1 = p_6_i_i_reg_268;

assign tmp_6_cast_i_i_fu_454_p1 = p_6_i_i_reg_268;

assign tmp_7_i_i_fu_458_p2 = ((tmp_6_cast_i_i_fu_454_p1 < op2_assign_reg_744) ? 1'b1 : 1'b0);

assign tmp_8_i_i_fu_476_p2 = ((p_2_i_i_reg_256 == 13'd2) ? 1'b1 : 1'b0);

assign tmp_9_i_i_fu_482_p2 = ((p_2_i_i_reg_256 == 13'd0) ? 1'b1 : 1'b0);

assign tmp_fu_534_p2 = (tmp_8_i_i_fu_476_p2 | sel_tmp2_fu_524_p2);

assign tmp_i_i_fu_488_p2 = ((p_2_i_i_reg_256 == 13'd1) ? 1'b1 : 1'b0);

always @ (posedge ap_clk) begin
    tmp_11_i_i_reg_785[31:13] <= 19'b0000000000000000000;
end

endmodule //a0_xFSobelFilter3x3
