// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module a0_xFSobel3x3_1_0_0_s (
        ap_clk,
        ap_rst,
        src_buf1_0_V_read,
        src_buf1_1_V_read,
        src_buf1_2_V_read,
        src_buf2_0_V_read,
        src_buf2_2_V_read,
        src_buf3_0_V_read,
        src_buf3_1_V_read,
        src_buf3_2_V_read,
        ap_return_0,
        ap_return_1,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [7:0] src_buf1_0_V_read;
input  [7:0] src_buf1_1_V_read;
input  [7:0] src_buf1_2_V_read;
input  [7:0] src_buf2_0_V_read;
input  [7:0] src_buf2_2_V_read;
input  [7:0] src_buf3_0_V_read;
input  [7:0] src_buf3_1_V_read;
input  [7:0] src_buf3_2_V_read;
output  [7:0] ap_return_0;
output  [7:0] ap_return_1;
input   ap_ce;

wire   [7:0] grp_xFGradientX3x3_0_0_s_fu_72_ap_return;
reg    grp_xFGradientX3x3_0_0_s_fu_72_ap_ce;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call8;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call8;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] grp_xFGradientY3x3_0_0_s_fu_88_ap_return;
reg    grp_xFGradientY3x3_0_0_s_fu_88_ap_ce;
wire    ap_block_pp0_stage0;

a0_xFGradientX3x3_0_0_s grp_xFGradientX3x3_0_0_s_fu_72(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0_V(src_buf1_0_V_read),
    .t2_V(src_buf1_2_V_read),
    .m0_V(src_buf2_0_V_read),
    .m2_V(src_buf2_2_V_read),
    .b0_V(src_buf3_0_V_read),
    .b2_V(src_buf3_2_V_read),
    .ap_return(grp_xFGradientX3x3_0_0_s_fu_72_ap_return),
    .ap_ce(grp_xFGradientX3x3_0_0_s_fu_72_ap_ce)
);

a0_xFGradientY3x3_0_0_s grp_xFGradientY3x3_0_0_s_fu_88(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .t0_V(src_buf1_0_V_read),
    .t1_V(src_buf1_1_V_read),
    .t2_V(src_buf1_2_V_read),
    .b0_V(src_buf3_0_V_read),
    .b1_V(src_buf3_1_V_read),
    .b2_V(src_buf3_2_V_read),
    .ap_return(grp_xFGradientY3x3_0_0_s_fu_88_ap_return),
    .ap_ce(grp_xFGradientY3x3_0_0_s_fu_88_ap_ce)
);

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_xFGradientX3x3_0_0_s_fu_72_ap_ce = 1'b1;
    end else begin
        grp_xFGradientX3x3_0_0_s_fu_72_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce))) begin
        grp_xFGradientY3x3_0_0_s_fu_88_ap_ce = 1'b1;
    end else begin
        grp_xFGradientY3x3_0_0_s_fu_88_ap_ce = 1'b0;
    end
end

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call8 = ~(1'b1 == 1'b1);

assign ap_return_0 = grp_xFGradientX3x3_0_0_s_fu_72_ap_return;

assign ap_return_1 = grp_xFGradientY3x3_0_0_s_fu_88_ap_return;

endmodule //a0_xFSobel3x3_1_0_0_s
