// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_Sobel.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_lv<19> a0_Sobel::ap_const_lv19_0 = "0000000000000000000";
const sc_logic a0_Sobel::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<8> a0_Sobel::ap_const_lv8_0 = "00000000";
const sc_logic a0_Sobel::ap_const_logic_1 = sc_dt::Log_1;

a0_Sobel::a0_Sobel(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Sobel_Loop_1_proc374_U0 = new a0_Sobel_Loop_1_proc374("Sobel_Loop_1_proc374_U0");
    Sobel_Loop_1_proc374_U0->ap_clk(ap_clk);
    Sobel_Loop_1_proc374_U0->ap_rst(ap_rst);
    Sobel_Loop_1_proc374_U0->ap_start(Sobel_Loop_1_proc374_U0_ap_start);
    Sobel_Loop_1_proc374_U0->start_full_n(Sobel_Loop_1_proc374_U0_start_full_n);
    Sobel_Loop_1_proc374_U0->ap_done(Sobel_Loop_1_proc374_U0_ap_done);
    Sobel_Loop_1_proc374_U0->ap_continue(Sobel_Loop_1_proc374_U0_ap_continue);
    Sobel_Loop_1_proc374_U0->ap_idle(Sobel_Loop_1_proc374_U0_ap_idle);
    Sobel_Loop_1_proc374_U0->ap_ready(Sobel_Loop_1_proc374_U0_ap_ready);
    Sobel_Loop_1_proc374_U0->start_out(Sobel_Loop_1_proc374_U0_start_out);
    Sobel_Loop_1_proc374_U0->start_write(Sobel_Loop_1_proc374_U0_start_write);
    Sobel_Loop_1_proc374_U0->p_src_mat_rows_read(p_src_mat_rows_read);
    Sobel_Loop_1_proc374_U0->p_src_mat_cols_read(p_src_mat_cols_read);
    Sobel_Loop_1_proc374_U0->p_src_mat_data_V_address0(Sobel_Loop_1_proc374_U0_p_src_mat_data_V_address0);
    Sobel_Loop_1_proc374_U0->p_src_mat_data_V_ce0(Sobel_Loop_1_proc374_U0_p_src_mat_data_V_ce0);
    Sobel_Loop_1_proc374_U0->p_src_mat_data_V_q0(p_src_mat_data_V_q0);
    Sobel_Loop_1_proc374_U0->p_src_V_V_din(Sobel_Loop_1_proc374_U0_p_src_V_V_din);
    Sobel_Loop_1_proc374_U0->p_src_V_V_full_n(p_src_V_V_full_n);
    Sobel_Loop_1_proc374_U0->p_src_V_V_write(Sobel_Loop_1_proc374_U0_p_src_V_V_write);
    Sobel_Loop_1_proc374_U0->p_dst_matx_rows_read(p_dst_matx_rows_read);
    Sobel_Loop_1_proc374_U0->p_dst_matx_cols_read(p_dst_matx_cols_read);
    Sobel_Loop_1_proc374_U0->p_dst_maty_cols_read(p_dst_maty_cols_read);
    Sobel_Loop_1_proc374_U0->p_src_mat_rows_read_out_din(Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_din);
    Sobel_Loop_1_proc374_U0->p_src_mat_rows_read_out_full_n(p_src_mat_rows_read_c_full_n);
    Sobel_Loop_1_proc374_U0->p_src_mat_rows_read_out_write(Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_write);
    Sobel_Loop_1_proc374_U0->p_src_mat_cols_read_out_din(Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_din);
    Sobel_Loop_1_proc374_U0->p_src_mat_cols_read_out_full_n(p_src_mat_cols_read_c_full_n);
    Sobel_Loop_1_proc374_U0->p_src_mat_cols_read_out_write(Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_write);
    Sobel_Loop_1_proc374_U0->p_dst_matx_rows_read_out_din(Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_din);
    Sobel_Loop_1_proc374_U0->p_dst_matx_rows_read_out_full_n(p_dst_matx_rows_read_s_full_n);
    Sobel_Loop_1_proc374_U0->p_dst_matx_rows_read_out_write(Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_write);
    Sobel_Loop_1_proc374_U0->p_dst_matx_cols_read_out_din(Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_din);
    Sobel_Loop_1_proc374_U0->p_dst_matx_cols_read_out_full_n(p_dst_matx_cols_read_s_full_n);
    Sobel_Loop_1_proc374_U0->p_dst_matx_cols_read_out_write(Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_write);
    Sobel_Loop_1_proc374_U0->p_dst_maty_cols_read_out_din(Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_din);
    Sobel_Loop_1_proc374_U0->p_dst_maty_cols_read_out_full_n(p_dst_maty_cols_read_s_full_n);
    Sobel_Loop_1_proc374_U0->p_dst_maty_cols_read_out_write(Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_write);
    xFSobelFilter3x3_U0 = new a0_xFSobelFilter3x3("xFSobelFilter3x3_U0");
    xFSobelFilter3x3_U0->ap_clk(ap_clk);
    xFSobelFilter3x3_U0->ap_rst(ap_rst);
    xFSobelFilter3x3_U0->ap_start(xFSobelFilter3x3_U0_ap_start);
    xFSobelFilter3x3_U0->ap_done(xFSobelFilter3x3_U0_ap_done);
    xFSobelFilter3x3_U0->ap_continue(xFSobelFilter3x3_U0_ap_continue);
    xFSobelFilter3x3_U0->ap_idle(xFSobelFilter3x3_U0_ap_idle);
    xFSobelFilter3x3_U0->ap_ready(xFSobelFilter3x3_U0_ap_ready);
    xFSobelFilter3x3_U0->p_src_mat_V_V_dout(p_src_V_V_dout);
    xFSobelFilter3x3_U0->p_src_mat_V_V_empty_n(p_src_V_V_empty_n);
    xFSobelFilter3x3_U0->p_src_mat_V_V_read(xFSobelFilter3x3_U0_p_src_mat_V_V_read);
    xFSobelFilter3x3_U0->p_gradx_mat_V_V_din(xFSobelFilter3x3_U0_p_gradx_mat_V_V_din);
    xFSobelFilter3x3_U0->p_gradx_mat_V_V_full_n(p_dstx_V_V_full_n);
    xFSobelFilter3x3_U0->p_gradx_mat_V_V_write(xFSobelFilter3x3_U0_p_gradx_mat_V_V_write);
    xFSobelFilter3x3_U0->p_grady_mat_V_V_din(xFSobelFilter3x3_U0_p_grady_mat_V_V_din);
    xFSobelFilter3x3_U0->p_grady_mat_V_V_full_n(p_dsty_V_V_full_n);
    xFSobelFilter3x3_U0->p_grady_mat_V_V_write(xFSobelFilter3x3_U0_p_grady_mat_V_V_write);
    xFSobelFilter3x3_U0->p_src_mat_rows_read_dout(p_src_mat_rows_read_c_dout);
    xFSobelFilter3x3_U0->p_src_mat_rows_read_empty_n(p_src_mat_rows_read_c_empty_n);
    xFSobelFilter3x3_U0->p_src_mat_rows_read_read(xFSobelFilter3x3_U0_p_src_mat_rows_read_read);
    xFSobelFilter3x3_U0->p_src_mat_cols_read_dout(p_src_mat_cols_read_c_dout);
    xFSobelFilter3x3_U0->p_src_mat_cols_read_empty_n(p_src_mat_cols_read_c_empty_n);
    xFSobelFilter3x3_U0->p_src_mat_cols_read_read(xFSobelFilter3x3_U0_p_src_mat_cols_read_read);
    Sobel_Loop_2_proc38_U0 = new a0_Sobel_Loop_2_proc38("Sobel_Loop_2_proc38_U0");
    Sobel_Loop_2_proc38_U0->ap_clk(ap_clk);
    Sobel_Loop_2_proc38_U0->ap_rst(ap_rst);
    Sobel_Loop_2_proc38_U0->ap_start(Sobel_Loop_2_proc38_U0_ap_start);
    Sobel_Loop_2_proc38_U0->ap_done(Sobel_Loop_2_proc38_U0_ap_done);
    Sobel_Loop_2_proc38_U0->ap_continue(Sobel_Loop_2_proc38_U0_ap_continue);
    Sobel_Loop_2_proc38_U0->ap_idle(Sobel_Loop_2_proc38_U0_ap_idle);
    Sobel_Loop_2_proc38_U0->ap_ready(Sobel_Loop_2_proc38_U0_ap_ready);
    Sobel_Loop_2_proc38_U0->p_dst_matx_rows_read_dout(p_dst_matx_rows_read_s_dout);
    Sobel_Loop_2_proc38_U0->p_dst_matx_rows_read_empty_n(p_dst_matx_rows_read_s_empty_n);
    Sobel_Loop_2_proc38_U0->p_dst_matx_rows_read_read(Sobel_Loop_2_proc38_U0_p_dst_matx_rows_read_read);
    Sobel_Loop_2_proc38_U0->p_dst_matx_cols_read_dout(p_dst_matx_cols_read_s_dout);
    Sobel_Loop_2_proc38_U0->p_dst_matx_cols_read_empty_n(p_dst_matx_cols_read_s_empty_n);
    Sobel_Loop_2_proc38_U0->p_dst_matx_cols_read_read(Sobel_Loop_2_proc38_U0_p_dst_matx_cols_read_read);
    Sobel_Loop_2_proc38_U0->p_dstx_V_V_dout(p_dstx_V_V_dout);
    Sobel_Loop_2_proc38_U0->p_dstx_V_V_empty_n(p_dstx_V_V_empty_n);
    Sobel_Loop_2_proc38_U0->p_dstx_V_V_read(Sobel_Loop_2_proc38_U0_p_dstx_V_V_read);
    Sobel_Loop_2_proc38_U0->p_dst_matx_data_V_address0(Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_address0);
    Sobel_Loop_2_proc38_U0->p_dst_matx_data_V_ce0(Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_ce0);
    Sobel_Loop_2_proc38_U0->p_dst_matx_data_V_we0(Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_we0);
    Sobel_Loop_2_proc38_U0->p_dst_matx_data_V_d0(Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_d0);
    Sobel_Loop_2_proc38_U0->p_dst_maty_cols_read_dout(p_dst_maty_cols_read_s_dout);
    Sobel_Loop_2_proc38_U0->p_dst_maty_cols_read_empty_n(p_dst_maty_cols_read_s_empty_n);
    Sobel_Loop_2_proc38_U0->p_dst_maty_cols_read_read(Sobel_Loop_2_proc38_U0_p_dst_maty_cols_read_read);
    Sobel_Loop_2_proc38_U0->p_dsty_V_V_dout(p_dsty_V_V_dout);
    Sobel_Loop_2_proc38_U0->p_dsty_V_V_empty_n(p_dsty_V_V_empty_n);
    Sobel_Loop_2_proc38_U0->p_dsty_V_V_read(Sobel_Loop_2_proc38_U0_p_dsty_V_V_read);
    Sobel_Loop_2_proc38_U0->p_dst_maty_data_V_address0(Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_address0);
    Sobel_Loop_2_proc38_U0->p_dst_maty_data_V_ce0(Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_ce0);
    Sobel_Loop_2_proc38_U0->p_dst_maty_data_V_we0(Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_we0);
    Sobel_Loop_2_proc38_U0->p_dst_maty_data_V_d0(Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_d0);
    p_src_V_V_U = new a0_fifo_w8_d2_A("p_src_V_V_U");
    p_src_V_V_U->clk(ap_clk);
    p_src_V_V_U->reset(ap_rst);
    p_src_V_V_U->if_read_ce(ap_var_for_const0);
    p_src_V_V_U->if_write_ce(ap_var_for_const0);
    p_src_V_V_U->if_din(Sobel_Loop_1_proc374_U0_p_src_V_V_din);
    p_src_V_V_U->if_full_n(p_src_V_V_full_n);
    p_src_V_V_U->if_write(Sobel_Loop_1_proc374_U0_p_src_V_V_write);
    p_src_V_V_U->if_dout(p_src_V_V_dout);
    p_src_V_V_U->if_empty_n(p_src_V_V_empty_n);
    p_src_V_V_U->if_read(xFSobelFilter3x3_U0_p_src_mat_V_V_read);
    p_src_mat_rows_read_c_U = new a0_fifo_w32_d2_A("p_src_mat_rows_read_c_U");
    p_src_mat_rows_read_c_U->clk(ap_clk);
    p_src_mat_rows_read_c_U->reset(ap_rst);
    p_src_mat_rows_read_c_U->if_read_ce(ap_var_for_const0);
    p_src_mat_rows_read_c_U->if_write_ce(ap_var_for_const0);
    p_src_mat_rows_read_c_U->if_din(Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_din);
    p_src_mat_rows_read_c_U->if_full_n(p_src_mat_rows_read_c_full_n);
    p_src_mat_rows_read_c_U->if_write(Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_write);
    p_src_mat_rows_read_c_U->if_dout(p_src_mat_rows_read_c_dout);
    p_src_mat_rows_read_c_U->if_empty_n(p_src_mat_rows_read_c_empty_n);
    p_src_mat_rows_read_c_U->if_read(xFSobelFilter3x3_U0_p_src_mat_rows_read_read);
    p_src_mat_cols_read_c_U = new a0_fifo_w32_d2_A("p_src_mat_cols_read_c_U");
    p_src_mat_cols_read_c_U->clk(ap_clk);
    p_src_mat_cols_read_c_U->reset(ap_rst);
    p_src_mat_cols_read_c_U->if_read_ce(ap_var_for_const0);
    p_src_mat_cols_read_c_U->if_write_ce(ap_var_for_const0);
    p_src_mat_cols_read_c_U->if_din(Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_din);
    p_src_mat_cols_read_c_U->if_full_n(p_src_mat_cols_read_c_full_n);
    p_src_mat_cols_read_c_U->if_write(Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_write);
    p_src_mat_cols_read_c_U->if_dout(p_src_mat_cols_read_c_dout);
    p_src_mat_cols_read_c_U->if_empty_n(p_src_mat_cols_read_c_empty_n);
    p_src_mat_cols_read_c_U->if_read(xFSobelFilter3x3_U0_p_src_mat_cols_read_read);
    p_dst_matx_rows_read_s_U = new a0_fifo_w32_d3_A("p_dst_matx_rows_read_s_U");
    p_dst_matx_rows_read_s_U->clk(ap_clk);
    p_dst_matx_rows_read_s_U->reset(ap_rst);
    p_dst_matx_rows_read_s_U->if_read_ce(ap_var_for_const0);
    p_dst_matx_rows_read_s_U->if_write_ce(ap_var_for_const0);
    p_dst_matx_rows_read_s_U->if_din(Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_din);
    p_dst_matx_rows_read_s_U->if_full_n(p_dst_matx_rows_read_s_full_n);
    p_dst_matx_rows_read_s_U->if_write(Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_write);
    p_dst_matx_rows_read_s_U->if_dout(p_dst_matx_rows_read_s_dout);
    p_dst_matx_rows_read_s_U->if_empty_n(p_dst_matx_rows_read_s_empty_n);
    p_dst_matx_rows_read_s_U->if_read(Sobel_Loop_2_proc38_U0_p_dst_matx_rows_read_read);
    p_dst_matx_cols_read_s_U = new a0_fifo_w32_d3_A("p_dst_matx_cols_read_s_U");
    p_dst_matx_cols_read_s_U->clk(ap_clk);
    p_dst_matx_cols_read_s_U->reset(ap_rst);
    p_dst_matx_cols_read_s_U->if_read_ce(ap_var_for_const0);
    p_dst_matx_cols_read_s_U->if_write_ce(ap_var_for_const0);
    p_dst_matx_cols_read_s_U->if_din(Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_din);
    p_dst_matx_cols_read_s_U->if_full_n(p_dst_matx_cols_read_s_full_n);
    p_dst_matx_cols_read_s_U->if_write(Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_write);
    p_dst_matx_cols_read_s_U->if_dout(p_dst_matx_cols_read_s_dout);
    p_dst_matx_cols_read_s_U->if_empty_n(p_dst_matx_cols_read_s_empty_n);
    p_dst_matx_cols_read_s_U->if_read(Sobel_Loop_2_proc38_U0_p_dst_matx_cols_read_read);
    p_dst_maty_cols_read_s_U = new a0_fifo_w32_d3_A("p_dst_maty_cols_read_s_U");
    p_dst_maty_cols_read_s_U->clk(ap_clk);
    p_dst_maty_cols_read_s_U->reset(ap_rst);
    p_dst_maty_cols_read_s_U->if_read_ce(ap_var_for_const0);
    p_dst_maty_cols_read_s_U->if_write_ce(ap_var_for_const0);
    p_dst_maty_cols_read_s_U->if_din(Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_din);
    p_dst_maty_cols_read_s_U->if_full_n(p_dst_maty_cols_read_s_full_n);
    p_dst_maty_cols_read_s_U->if_write(Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_write);
    p_dst_maty_cols_read_s_U->if_dout(p_dst_maty_cols_read_s_dout);
    p_dst_maty_cols_read_s_U->if_empty_n(p_dst_maty_cols_read_s_empty_n);
    p_dst_maty_cols_read_s_U->if_read(Sobel_Loop_2_proc38_U0_p_dst_maty_cols_read_read);
    p_dstx_V_V_U = new a0_fifo_w8_d2_A("p_dstx_V_V_U");
    p_dstx_V_V_U->clk(ap_clk);
    p_dstx_V_V_U->reset(ap_rst);
    p_dstx_V_V_U->if_read_ce(ap_var_for_const0);
    p_dstx_V_V_U->if_write_ce(ap_var_for_const0);
    p_dstx_V_V_U->if_din(xFSobelFilter3x3_U0_p_gradx_mat_V_V_din);
    p_dstx_V_V_U->if_full_n(p_dstx_V_V_full_n);
    p_dstx_V_V_U->if_write(xFSobelFilter3x3_U0_p_gradx_mat_V_V_write);
    p_dstx_V_V_U->if_dout(p_dstx_V_V_dout);
    p_dstx_V_V_U->if_empty_n(p_dstx_V_V_empty_n);
    p_dstx_V_V_U->if_read(Sobel_Loop_2_proc38_U0_p_dstx_V_V_read);
    p_dsty_V_V_U = new a0_fifo_w8_d2_A("p_dsty_V_V_U");
    p_dsty_V_V_U->clk(ap_clk);
    p_dsty_V_V_U->reset(ap_rst);
    p_dsty_V_V_U->if_read_ce(ap_var_for_const0);
    p_dsty_V_V_U->if_write_ce(ap_var_for_const0);
    p_dsty_V_V_U->if_din(xFSobelFilter3x3_U0_p_grady_mat_V_V_din);
    p_dsty_V_V_U->if_full_n(p_dsty_V_V_full_n);
    p_dsty_V_V_U->if_write(xFSobelFilter3x3_U0_p_grady_mat_V_V_write);
    p_dsty_V_V_U->if_dout(p_dsty_V_V_dout);
    p_dsty_V_V_U->if_empty_n(p_dsty_V_V_empty_n);
    p_dsty_V_V_U->if_read(Sobel_Loop_2_proc38_U0_p_dsty_V_V_read);
    start_for_xFSobelfYi_U = new a0_start_for_xFSobelfYi("start_for_xFSobelfYi_U");
    start_for_xFSobelfYi_U->clk(ap_clk);
    start_for_xFSobelfYi_U->reset(ap_rst);
    start_for_xFSobelfYi_U->if_read_ce(ap_var_for_const0);
    start_for_xFSobelfYi_U->if_write_ce(ap_var_for_const0);
    start_for_xFSobelfYi_U->if_din(start_for_xFSobelFilter3x3_U0_din);
    start_for_xFSobelfYi_U->if_full_n(start_for_xFSobelFilter3x3_U0_full_n);
    start_for_xFSobelfYi_U->if_write(Sobel_Loop_1_proc374_U0_start_write);
    start_for_xFSobelfYi_U->if_dout(start_for_xFSobelFilter3x3_U0_dout);
    start_for_xFSobelfYi_U->if_empty_n(start_for_xFSobelFilter3x3_U0_empty_n);
    start_for_xFSobelfYi_U->if_read(xFSobelFilter3x3_U0_ap_ready);
    start_for_Sobel_Lg8j_U = new a0_start_for_Sobel_Lg8j("start_for_Sobel_Lg8j_U");
    start_for_Sobel_Lg8j_U->clk(ap_clk);
    start_for_Sobel_Lg8j_U->reset(ap_rst);
    start_for_Sobel_Lg8j_U->if_read_ce(ap_var_for_const0);
    start_for_Sobel_Lg8j_U->if_write_ce(ap_var_for_const0);
    start_for_Sobel_Lg8j_U->if_din(start_for_Sobel_Loop_2_proc38_U0_din);
    start_for_Sobel_Lg8j_U->if_full_n(start_for_Sobel_Loop_2_proc38_U0_full_n);
    start_for_Sobel_Lg8j_U->if_write(Sobel_Loop_1_proc374_U0_start_write);
    start_for_Sobel_Lg8j_U->if_dout(start_for_Sobel_Loop_2_proc38_U0_dout);
    start_for_Sobel_Lg8j_U->if_empty_n(start_for_Sobel_Loop_2_proc38_U0_empty_n);
    start_for_Sobel_Lg8j_U->if_read(Sobel_Loop_2_proc38_U0_ap_ready);

    SC_METHOD(thread_Sobel_Loop_1_proc374_U0_ap_continue);

    SC_METHOD(thread_Sobel_Loop_1_proc374_U0_ap_start);
    sensitive << ( ap_start );

    SC_METHOD(thread_Sobel_Loop_1_proc374_U0_start_full_n);
    sensitive << ( start_for_xFSobelFilter3x3_U0_full_n );
    sensitive << ( start_for_Sobel_Loop_2_proc38_U0_full_n );

    SC_METHOD(thread_Sobel_Loop_2_proc38_U0_ap_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_Sobel_Loop_2_proc38_U0_ap_start);
    sensitive << ( start_for_Sobel_Loop_2_proc38_U0_empty_n );

    SC_METHOD(thread_Sobel_Loop_2_proc38_U0_start_full_n);

    SC_METHOD(thread_Sobel_Loop_2_proc38_U0_start_write);

    SC_METHOD(thread_ap_done);
    sensitive << ( Sobel_Loop_2_proc38_U0_ap_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Sobel_Loop_1_proc374_U0_ap_idle );
    sensitive << ( xFSobelFilter3x3_U0_ap_idle );
    sensitive << ( Sobel_Loop_2_proc38_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( Sobel_Loop_1_proc374_U0_ap_ready );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_continue );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Sobel_Loop_2_proc38_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( Sobel_Loop_1_proc374_U0_ap_ready );

    SC_METHOD(thread_p_dst_matx_data_V_address0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_address0 );

    SC_METHOD(thread_p_dst_matx_data_V_address1);

    SC_METHOD(thread_p_dst_matx_data_V_ce0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_ce0 );

    SC_METHOD(thread_p_dst_matx_data_V_ce1);

    SC_METHOD(thread_p_dst_matx_data_V_d0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_d0 );

    SC_METHOD(thread_p_dst_matx_data_V_d1);

    SC_METHOD(thread_p_dst_matx_data_V_we0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_we0 );

    SC_METHOD(thread_p_dst_matx_data_V_we1);

    SC_METHOD(thread_p_dst_maty_data_V_address0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_address0 );

    SC_METHOD(thread_p_dst_maty_data_V_address1);

    SC_METHOD(thread_p_dst_maty_data_V_ce0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_ce0 );

    SC_METHOD(thread_p_dst_maty_data_V_ce1);

    SC_METHOD(thread_p_dst_maty_data_V_d0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_d0 );

    SC_METHOD(thread_p_dst_maty_data_V_d1);

    SC_METHOD(thread_p_dst_maty_data_V_we0);
    sensitive << ( Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_we0 );

    SC_METHOD(thread_p_dst_maty_data_V_we1);

    SC_METHOD(thread_p_src_mat_data_V_address0);
    sensitive << ( Sobel_Loop_1_proc374_U0_p_src_mat_data_V_address0 );

    SC_METHOD(thread_p_src_mat_data_V_address1);

    SC_METHOD(thread_p_src_mat_data_V_ce0);
    sensitive << ( Sobel_Loop_1_proc374_U0_p_src_mat_data_V_ce0 );

    SC_METHOD(thread_p_src_mat_data_V_ce1);

    SC_METHOD(thread_p_src_mat_data_V_d0);

    SC_METHOD(thread_p_src_mat_data_V_d1);

    SC_METHOD(thread_p_src_mat_data_V_we0);

    SC_METHOD(thread_p_src_mat_data_V_we1);

    SC_METHOD(thread_start_for_Sobel_Loop_2_proc38_U0_din);

    SC_METHOD(thread_start_for_xFSobelFilter3x3_U0_din);

    SC_METHOD(thread_xFSobelFilter3x3_U0_ap_continue);

    SC_METHOD(thread_xFSobelFilter3x3_U0_ap_start);
    sensitive << ( start_for_xFSobelFilter3x3_U0_empty_n );

    SC_METHOD(thread_xFSobelFilter3x3_U0_start_full_n);

    SC_METHOD(thread_xFSobelFilter3x3_U0_start_write);

    SC_THREAD(thread_ap_var_for_const0);

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_Sobel_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, p_src_mat_rows_read, "(port)p_src_mat_rows_read");
    sc_trace(mVcdFile, p_src_mat_cols_read, "(port)p_src_mat_cols_read");
    sc_trace(mVcdFile, p_src_mat_data_V_address0, "(port)p_src_mat_data_V_address0");
    sc_trace(mVcdFile, p_src_mat_data_V_ce0, "(port)p_src_mat_data_V_ce0");
    sc_trace(mVcdFile, p_src_mat_data_V_d0, "(port)p_src_mat_data_V_d0");
    sc_trace(mVcdFile, p_src_mat_data_V_q0, "(port)p_src_mat_data_V_q0");
    sc_trace(mVcdFile, p_src_mat_data_V_we0, "(port)p_src_mat_data_V_we0");
    sc_trace(mVcdFile, p_src_mat_data_V_address1, "(port)p_src_mat_data_V_address1");
    sc_trace(mVcdFile, p_src_mat_data_V_ce1, "(port)p_src_mat_data_V_ce1");
    sc_trace(mVcdFile, p_src_mat_data_V_d1, "(port)p_src_mat_data_V_d1");
    sc_trace(mVcdFile, p_src_mat_data_V_q1, "(port)p_src_mat_data_V_q1");
    sc_trace(mVcdFile, p_src_mat_data_V_we1, "(port)p_src_mat_data_V_we1");
    sc_trace(mVcdFile, p_dst_matx_rows_read, "(port)p_dst_matx_rows_read");
    sc_trace(mVcdFile, p_dst_matx_cols_read, "(port)p_dst_matx_cols_read");
    sc_trace(mVcdFile, p_dst_matx_data_V_address0, "(port)p_dst_matx_data_V_address0");
    sc_trace(mVcdFile, p_dst_matx_data_V_ce0, "(port)p_dst_matx_data_V_ce0");
    sc_trace(mVcdFile, p_dst_matx_data_V_d0, "(port)p_dst_matx_data_V_d0");
    sc_trace(mVcdFile, p_dst_matx_data_V_q0, "(port)p_dst_matx_data_V_q0");
    sc_trace(mVcdFile, p_dst_matx_data_V_we0, "(port)p_dst_matx_data_V_we0");
    sc_trace(mVcdFile, p_dst_matx_data_V_address1, "(port)p_dst_matx_data_V_address1");
    sc_trace(mVcdFile, p_dst_matx_data_V_ce1, "(port)p_dst_matx_data_V_ce1");
    sc_trace(mVcdFile, p_dst_matx_data_V_d1, "(port)p_dst_matx_data_V_d1");
    sc_trace(mVcdFile, p_dst_matx_data_V_q1, "(port)p_dst_matx_data_V_q1");
    sc_trace(mVcdFile, p_dst_matx_data_V_we1, "(port)p_dst_matx_data_V_we1");
    sc_trace(mVcdFile, p_dst_maty_cols_read, "(port)p_dst_maty_cols_read");
    sc_trace(mVcdFile, p_dst_maty_data_V_address0, "(port)p_dst_maty_data_V_address0");
    sc_trace(mVcdFile, p_dst_maty_data_V_ce0, "(port)p_dst_maty_data_V_ce0");
    sc_trace(mVcdFile, p_dst_maty_data_V_d0, "(port)p_dst_maty_data_V_d0");
    sc_trace(mVcdFile, p_dst_maty_data_V_q0, "(port)p_dst_maty_data_V_q0");
    sc_trace(mVcdFile, p_dst_maty_data_V_we0, "(port)p_dst_maty_data_V_we0");
    sc_trace(mVcdFile, p_dst_maty_data_V_address1, "(port)p_dst_maty_data_V_address1");
    sc_trace(mVcdFile, p_dst_maty_data_V_ce1, "(port)p_dst_maty_data_V_ce1");
    sc_trace(mVcdFile, p_dst_maty_data_V_d1, "(port)p_dst_maty_data_V_d1");
    sc_trace(mVcdFile, p_dst_maty_data_V_q1, "(port)p_dst_maty_data_V_q1");
    sc_trace(mVcdFile, p_dst_maty_data_V_we1, "(port)p_dst_maty_data_V_we1");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, p_src_mat_rows_read_ap_vld, "(port)p_src_mat_rows_read_ap_vld");
    sc_trace(mVcdFile, p_src_mat_cols_read_ap_vld, "(port)p_src_mat_cols_read_ap_vld");
    sc_trace(mVcdFile, p_dst_matx_rows_read_ap_vld, "(port)p_dst_matx_rows_read_ap_vld");
    sc_trace(mVcdFile, p_dst_matx_cols_read_ap_vld, "(port)p_dst_matx_cols_read_ap_vld");
    sc_trace(mVcdFile, p_dst_maty_cols_read_ap_vld, "(port)p_dst_maty_cols_read_ap_vld");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_ap_start, "Sobel_Loop_1_proc374_U0_ap_start");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_start_full_n, "Sobel_Loop_1_proc374_U0_start_full_n");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_ap_done, "Sobel_Loop_1_proc374_U0_ap_done");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_ap_continue, "Sobel_Loop_1_proc374_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_ap_idle, "Sobel_Loop_1_proc374_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_ap_ready, "Sobel_Loop_1_proc374_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_start_out, "Sobel_Loop_1_proc374_U0_start_out");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_start_write, "Sobel_Loop_1_proc374_U0_start_write");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_mat_data_V_address0, "Sobel_Loop_1_proc374_U0_p_src_mat_data_V_address0");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_mat_data_V_ce0, "Sobel_Loop_1_proc374_U0_p_src_mat_data_V_ce0");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_V_V_din, "Sobel_Loop_1_proc374_U0_p_src_V_V_din");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_V_V_write, "Sobel_Loop_1_proc374_U0_p_src_V_V_write");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_din, "Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_din");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_write, "Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_write");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_din, "Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_din");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_write, "Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_write");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_din, "Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_din");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_write, "Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_write");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_din, "Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_din");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_write, "Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_write");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_din, "Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_din");
    sc_trace(mVcdFile, Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_write, "Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_write");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_ap_start, "xFSobelFilter3x3_U0_ap_start");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_ap_done, "xFSobelFilter3x3_U0_ap_done");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_ap_continue, "xFSobelFilter3x3_U0_ap_continue");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_ap_idle, "xFSobelFilter3x3_U0_ap_idle");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_ap_ready, "xFSobelFilter3x3_U0_ap_ready");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_src_mat_V_V_read, "xFSobelFilter3x3_U0_p_src_mat_V_V_read");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_gradx_mat_V_V_din, "xFSobelFilter3x3_U0_p_gradx_mat_V_V_din");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_gradx_mat_V_V_write, "xFSobelFilter3x3_U0_p_gradx_mat_V_V_write");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_grady_mat_V_V_din, "xFSobelFilter3x3_U0_p_grady_mat_V_V_din");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_grady_mat_V_V_write, "xFSobelFilter3x3_U0_p_grady_mat_V_V_write");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_src_mat_rows_read_read, "xFSobelFilter3x3_U0_p_src_mat_rows_read_read");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_p_src_mat_cols_read_read, "xFSobelFilter3x3_U0_p_src_mat_cols_read_read");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_ap_start, "Sobel_Loop_2_proc38_U0_ap_start");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_ap_done, "Sobel_Loop_2_proc38_U0_ap_done");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_ap_continue, "Sobel_Loop_2_proc38_U0_ap_continue");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_ap_idle, "Sobel_Loop_2_proc38_U0_ap_idle");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_ap_ready, "Sobel_Loop_2_proc38_U0_ap_ready");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_matx_rows_read_read, "Sobel_Loop_2_proc38_U0_p_dst_matx_rows_read_read");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_matx_cols_read_read, "Sobel_Loop_2_proc38_U0_p_dst_matx_cols_read_read");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dstx_V_V_read, "Sobel_Loop_2_proc38_U0_p_dstx_V_V_read");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_address0, "Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_address0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_ce0, "Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_ce0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_we0, "Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_we0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_d0, "Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_d0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_maty_cols_read_read, "Sobel_Loop_2_proc38_U0_p_dst_maty_cols_read_read");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dsty_V_V_read, "Sobel_Loop_2_proc38_U0_p_dsty_V_V_read");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_address0, "Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_address0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_ce0, "Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_ce0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_we0, "Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_we0");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_d0, "Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_d0");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, p_src_V_V_full_n, "p_src_V_V_full_n");
    sc_trace(mVcdFile, p_src_V_V_dout, "p_src_V_V_dout");
    sc_trace(mVcdFile, p_src_V_V_empty_n, "p_src_V_V_empty_n");
    sc_trace(mVcdFile, p_src_mat_rows_read_c_full_n, "p_src_mat_rows_read_c_full_n");
    sc_trace(mVcdFile, p_src_mat_rows_read_c_dout, "p_src_mat_rows_read_c_dout");
    sc_trace(mVcdFile, p_src_mat_rows_read_c_empty_n, "p_src_mat_rows_read_c_empty_n");
    sc_trace(mVcdFile, p_src_mat_cols_read_c_full_n, "p_src_mat_cols_read_c_full_n");
    sc_trace(mVcdFile, p_src_mat_cols_read_c_dout, "p_src_mat_cols_read_c_dout");
    sc_trace(mVcdFile, p_src_mat_cols_read_c_empty_n, "p_src_mat_cols_read_c_empty_n");
    sc_trace(mVcdFile, p_dst_matx_rows_read_s_full_n, "p_dst_matx_rows_read_s_full_n");
    sc_trace(mVcdFile, p_dst_matx_rows_read_s_dout, "p_dst_matx_rows_read_s_dout");
    sc_trace(mVcdFile, p_dst_matx_rows_read_s_empty_n, "p_dst_matx_rows_read_s_empty_n");
    sc_trace(mVcdFile, p_dst_matx_cols_read_s_full_n, "p_dst_matx_cols_read_s_full_n");
    sc_trace(mVcdFile, p_dst_matx_cols_read_s_dout, "p_dst_matx_cols_read_s_dout");
    sc_trace(mVcdFile, p_dst_matx_cols_read_s_empty_n, "p_dst_matx_cols_read_s_empty_n");
    sc_trace(mVcdFile, p_dst_maty_cols_read_s_full_n, "p_dst_maty_cols_read_s_full_n");
    sc_trace(mVcdFile, p_dst_maty_cols_read_s_dout, "p_dst_maty_cols_read_s_dout");
    sc_trace(mVcdFile, p_dst_maty_cols_read_s_empty_n, "p_dst_maty_cols_read_s_empty_n");
    sc_trace(mVcdFile, p_dstx_V_V_full_n, "p_dstx_V_V_full_n");
    sc_trace(mVcdFile, p_dstx_V_V_dout, "p_dstx_V_V_dout");
    sc_trace(mVcdFile, p_dstx_V_V_empty_n, "p_dstx_V_V_empty_n");
    sc_trace(mVcdFile, p_dsty_V_V_full_n, "p_dsty_V_V_full_n");
    sc_trace(mVcdFile, p_dsty_V_V_dout, "p_dsty_V_V_dout");
    sc_trace(mVcdFile, p_dsty_V_V_empty_n, "p_dsty_V_V_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, start_for_xFSobelFilter3x3_U0_din, "start_for_xFSobelFilter3x3_U0_din");
    sc_trace(mVcdFile, start_for_xFSobelFilter3x3_U0_full_n, "start_for_xFSobelFilter3x3_U0_full_n");
    sc_trace(mVcdFile, start_for_xFSobelFilter3x3_U0_dout, "start_for_xFSobelFilter3x3_U0_dout");
    sc_trace(mVcdFile, start_for_xFSobelFilter3x3_U0_empty_n, "start_for_xFSobelFilter3x3_U0_empty_n");
    sc_trace(mVcdFile, start_for_Sobel_Loop_2_proc38_U0_din, "start_for_Sobel_Loop_2_proc38_U0_din");
    sc_trace(mVcdFile, start_for_Sobel_Loop_2_proc38_U0_full_n, "start_for_Sobel_Loop_2_proc38_U0_full_n");
    sc_trace(mVcdFile, start_for_Sobel_Loop_2_proc38_U0_dout, "start_for_Sobel_Loop_2_proc38_U0_dout");
    sc_trace(mVcdFile, start_for_Sobel_Loop_2_proc38_U0_empty_n, "start_for_Sobel_Loop_2_proc38_U0_empty_n");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_start_full_n, "xFSobelFilter3x3_U0_start_full_n");
    sc_trace(mVcdFile, xFSobelFilter3x3_U0_start_write, "xFSobelFilter3x3_U0_start_write");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_start_full_n, "Sobel_Loop_2_proc38_U0_start_full_n");
    sc_trace(mVcdFile, Sobel_Loop_2_proc38_U0_start_write, "Sobel_Loop_2_proc38_U0_start_write");
#endif

    }
}

a0_Sobel::~a0_Sobel() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete Sobel_Loop_1_proc374_U0;
    delete xFSobelFilter3x3_U0;
    delete Sobel_Loop_2_proc38_U0;
    delete p_src_V_V_U;
    delete p_src_mat_rows_read_c_U;
    delete p_src_mat_cols_read_c_U;
    delete p_dst_matx_rows_read_s_U;
    delete p_dst_matx_cols_read_s_U;
    delete p_dst_maty_cols_read_s_U;
    delete p_dstx_V_V_U;
    delete p_dsty_V_V_U;
    delete start_for_xFSobelfYi_U;
    delete start_for_Sobel_Lg8j_U;
}

void a0_Sobel::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void a0_Sobel::thread_Sobel_Loop_1_proc374_U0_ap_continue() {
    Sobel_Loop_1_proc374_U0_ap_continue = ap_const_logic_1;
}

void a0_Sobel::thread_Sobel_Loop_1_proc374_U0_ap_start() {
    Sobel_Loop_1_proc374_U0_ap_start = ap_start.read();
}

void a0_Sobel::thread_Sobel_Loop_1_proc374_U0_start_full_n() {
    Sobel_Loop_1_proc374_U0_start_full_n = (start_for_xFSobelFilter3x3_U0_full_n.read() & start_for_Sobel_Loop_2_proc38_U0_full_n.read());
}

void a0_Sobel::thread_Sobel_Loop_2_proc38_U0_ap_continue() {
    Sobel_Loop_2_proc38_U0_ap_continue = ap_continue.read();
}

void a0_Sobel::thread_Sobel_Loop_2_proc38_U0_ap_start() {
    Sobel_Loop_2_proc38_U0_ap_start = start_for_Sobel_Loop_2_proc38_U0_empty_n.read();
}

void a0_Sobel::thread_Sobel_Loop_2_proc38_U0_start_full_n() {
    Sobel_Loop_2_proc38_U0_start_full_n = ap_const_logic_1;
}

void a0_Sobel::thread_Sobel_Loop_2_proc38_U0_start_write() {
    Sobel_Loop_2_proc38_U0_start_write = ap_const_logic_0;
}

void a0_Sobel::thread_ap_done() {
    ap_done = Sobel_Loop_2_proc38_U0_ap_done.read();
}

void a0_Sobel::thread_ap_idle() {
    ap_idle = (Sobel_Loop_1_proc374_U0_ap_idle.read() & xFSobelFilter3x3_U0_ap_idle.read() & Sobel_Loop_2_proc38_U0_ap_idle.read());
}

void a0_Sobel::thread_ap_ready() {
    ap_ready = Sobel_Loop_1_proc374_U0_ap_ready.read();
}

void a0_Sobel::thread_ap_sync_continue() {
    ap_sync_continue = ap_continue.read();
}

void a0_Sobel::thread_ap_sync_done() {
    ap_sync_done = Sobel_Loop_2_proc38_U0_ap_done.read();
}

void a0_Sobel::thread_ap_sync_ready() {
    ap_sync_ready = Sobel_Loop_1_proc374_U0_ap_ready.read();
}

void a0_Sobel::thread_p_dst_matx_data_V_address0() {
    p_dst_matx_data_V_address0 = Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_address0.read();
}

void a0_Sobel::thread_p_dst_matx_data_V_address1() {
    p_dst_matx_data_V_address1 = ap_const_lv19_0;
}

void a0_Sobel::thread_p_dst_matx_data_V_ce0() {
    p_dst_matx_data_V_ce0 = Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_ce0.read();
}

void a0_Sobel::thread_p_dst_matx_data_V_ce1() {
    p_dst_matx_data_V_ce1 = ap_const_logic_0;
}

void a0_Sobel::thread_p_dst_matx_data_V_d0() {
    p_dst_matx_data_V_d0 = Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_d0.read();
}

void a0_Sobel::thread_p_dst_matx_data_V_d1() {
    p_dst_matx_data_V_d1 = ap_const_lv8_0;
}

void a0_Sobel::thread_p_dst_matx_data_V_we0() {
    p_dst_matx_data_V_we0 = Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_we0.read();
}

void a0_Sobel::thread_p_dst_matx_data_V_we1() {
    p_dst_matx_data_V_we1 = ap_const_logic_0;
}

void a0_Sobel::thread_p_dst_maty_data_V_address0() {
    p_dst_maty_data_V_address0 = Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_address0.read();
}

void a0_Sobel::thread_p_dst_maty_data_V_address1() {
    p_dst_maty_data_V_address1 = ap_const_lv19_0;
}

void a0_Sobel::thread_p_dst_maty_data_V_ce0() {
    p_dst_maty_data_V_ce0 = Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_ce0.read();
}

void a0_Sobel::thread_p_dst_maty_data_V_ce1() {
    p_dst_maty_data_V_ce1 = ap_const_logic_0;
}

void a0_Sobel::thread_p_dst_maty_data_V_d0() {
    p_dst_maty_data_V_d0 = Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_d0.read();
}

void a0_Sobel::thread_p_dst_maty_data_V_d1() {
    p_dst_maty_data_V_d1 = ap_const_lv8_0;
}

void a0_Sobel::thread_p_dst_maty_data_V_we0() {
    p_dst_maty_data_V_we0 = Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_we0.read();
}

void a0_Sobel::thread_p_dst_maty_data_V_we1() {
    p_dst_maty_data_V_we1 = ap_const_logic_0;
}

void a0_Sobel::thread_p_src_mat_data_V_address0() {
    p_src_mat_data_V_address0 = Sobel_Loop_1_proc374_U0_p_src_mat_data_V_address0.read();
}

void a0_Sobel::thread_p_src_mat_data_V_address1() {
    p_src_mat_data_V_address1 = ap_const_lv19_0;
}

void a0_Sobel::thread_p_src_mat_data_V_ce0() {
    p_src_mat_data_V_ce0 = Sobel_Loop_1_proc374_U0_p_src_mat_data_V_ce0.read();
}

void a0_Sobel::thread_p_src_mat_data_V_ce1() {
    p_src_mat_data_V_ce1 = ap_const_logic_0;
}

void a0_Sobel::thread_p_src_mat_data_V_d0() {
    p_src_mat_data_V_d0 = ap_const_lv8_0;
}

void a0_Sobel::thread_p_src_mat_data_V_d1() {
    p_src_mat_data_V_d1 = ap_const_lv8_0;
}

void a0_Sobel::thread_p_src_mat_data_V_we0() {
    p_src_mat_data_V_we0 = ap_const_logic_0;
}

void a0_Sobel::thread_p_src_mat_data_V_we1() {
    p_src_mat_data_V_we1 = ap_const_logic_0;
}

void a0_Sobel::thread_start_for_Sobel_Loop_2_proc38_U0_din() {
    start_for_Sobel_Loop_2_proc38_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void a0_Sobel::thread_start_for_xFSobelFilter3x3_U0_din() {
    start_for_xFSobelFilter3x3_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void a0_Sobel::thread_xFSobelFilter3x3_U0_ap_continue() {
    xFSobelFilter3x3_U0_ap_continue = ap_const_logic_1;
}

void a0_Sobel::thread_xFSobelFilter3x3_U0_ap_start() {
    xFSobelFilter3x3_U0_ap_start = start_for_xFSobelFilter3x3_U0_empty_n.read();
}

void a0_Sobel::thread_xFSobelFilter3x3_U0_start_full_n() {
    xFSobelFilter3x3_U0_start_full_n = ap_const_logic_1;
}

void a0_Sobel::thread_xFSobelFilter3x3_U0_start_write() {
    xFSobelFilter3x3_U0_start_write = ap_const_logic_0;
}

}

