// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_Sobel_Loop_1_proc374.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic a0_Sobel_Loop_1_proc374::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic a0_Sobel_Loop_1_proc374::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<4> a0_Sobel_Loop_1_proc374::ap_ST_fsm_state1 = "1";
const sc_lv<4> a0_Sobel_Loop_1_proc374::ap_ST_fsm_state2 = "10";
const sc_lv<4> a0_Sobel_Loop_1_proc374::ap_ST_fsm_pp0_stage0 = "100";
const sc_lv<4> a0_Sobel_Loop_1_proc374::ap_ST_fsm_state5 = "1000";
const bool a0_Sobel_Loop_1_proc374::ap_const_boolean_1 = true;
const sc_lv<32> a0_Sobel_Loop_1_proc374::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> a0_Sobel_Loop_1_proc374::ap_const_lv32_2 = "10";
const bool a0_Sobel_Loop_1_proc374::ap_const_boolean_0 = false;
const sc_lv<1> a0_Sobel_Loop_1_proc374::ap_const_lv1_1 = "1";
const sc_lv<32> a0_Sobel_Loop_1_proc374::ap_const_lv32_1 = "1";
const sc_lv<1> a0_Sobel_Loop_1_proc374::ap_const_lv1_0 = "0";
const sc_lv<31> a0_Sobel_Loop_1_proc374::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<32> a0_Sobel_Loop_1_proc374::ap_const_lv32_3 = "11";
const sc_lv<31> a0_Sobel_Loop_1_proc374::ap_const_lv31_1 = "1";

a0_Sobel_Loop_1_proc374::a0_Sobel_Loop_1_proc374(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_01001);
    sensitive << ( p_src_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_i_i_36_reg_264 );

    SC_METHOD(thread_ap_block_pp0_stage0_11001);
    sensitive << ( p_src_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_i_i_36_reg_264 );

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);
    sensitive << ( p_src_V_V_full_n );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_i_i_36_reg_264 );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_ap_block_state3_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);
    sensitive << ( p_src_V_V_full_n );
    sensitive << ( tmp_i_i_36_reg_264 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state3);
    sensitive << ( tmp_i_i_36_fu_214_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( tmp_i_i_fu_190_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( real_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( internal_ap_ready );

    SC_METHOD(thread_i_cast_i_i_fu_182_p1);
    sensitive << ( i_i_i_reg_156 );

    SC_METHOD(thread_i_fu_195_p2);
    sensitive << ( i_i_i_reg_156 );

    SC_METHOD(thread_internal_ap_ready);
    sensitive << ( tmp_i_i_fu_190_p2 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_j_cast_i_i_fu_206_p1);
    sensitive << ( j_i_i_reg_167 );

    SC_METHOD(thread_j_fu_219_p2);
    sensitive << ( j_i_i_reg_167 );

    SC_METHOD(thread_p_dst_matx_cols_read_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_dst_matx_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_matx_cols_read_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_dst_matx_cols_read );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_matx_cols_read_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_matx_rows_read_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_dst_matx_rows_read_out_full_n );

    SC_METHOD(thread_p_dst_matx_rows_read_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_dst_matx_rows_read );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_matx_rows_read_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_maty_cols_read_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_maty_cols_read_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_dst_maty_cols_read );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_dst_maty_cols_read_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_src_V_V_blk_n);
    sensitive << ( p_src_V_V_full_n );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_i_i_36_reg_264 );

    SC_METHOD(thread_p_src_V_V_din);
    sensitive << ( p_src_mat_data_V_q0 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_i_i_36_reg_264 );
    sensitive << ( ap_block_pp0_stage0_01001 );

    SC_METHOD(thread_p_src_V_V_write);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( tmp_i_i_36_reg_264 );
    sensitive << ( ap_block_pp0_stage0_11001 );

    SC_METHOD(thread_p_src_mat_cols_read_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_cols_read_out_full_n );

    SC_METHOD(thread_p_src_mat_cols_read_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_cols_read );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_src_mat_cols_read_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_src_mat_data_V_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( p_sum1_cast_i_i_fu_230_p1 );

    SC_METHOD(thread_p_src_mat_data_V_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_p_src_mat_rows_read_out_blk_n);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );

    SC_METHOD(thread_p_src_mat_rows_read_out_din);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_src_mat_rows_read_out_write);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );

    SC_METHOD(thread_p_sum1_cast_i_i_fu_230_p1);
    sensitive << ( p_sum1_i_i_fu_225_p2 );

    SC_METHOD(thread_p_sum1_i_i_fu_225_p2);
    sensitive << ( tmp_21_i_i_reg_259 );
    sensitive << ( tmp_14_fu_210_p1 );

    SC_METHOD(thread_real_start);
    sensitive << ( ap_start );
    sensitive << ( start_full_n );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_start_out);
    sensitive << ( real_start );

    SC_METHOD(thread_start_write);
    sensitive << ( real_start );
    sensitive << ( start_once_reg );

    SC_METHOD(thread_tmp_13_fu_186_p1);
    sensitive << ( i_i_i_reg_156 );

    SC_METHOD(thread_tmp_14_fu_210_p1);
    sensitive << ( j_i_i_reg_167 );

    SC_METHOD(thread_tmp_21_i_i_fu_201_p2);
    sensitive << ( tmp_reg_245 );
    sensitive << ( tmp_13_fu_186_p1 );

    SC_METHOD(thread_tmp_fu_178_p1);
    sensitive << ( p_src_mat_cols_read );

    SC_METHOD(thread_tmp_i_i_36_fu_214_p2);
    sensitive << ( p_src_mat_cols_read );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( j_cast_i_i_fu_206_p1 );

    SC_METHOD(thread_tmp_i_i_fu_190_p2);
    sensitive << ( p_src_mat_rows_read );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_cast_i_i_fu_182_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( real_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( p_src_mat_rows_read_out_full_n );
    sensitive << ( p_src_mat_cols_read_out_full_n );
    sensitive << ( p_dst_matx_rows_read_out_full_n );
    sensitive << ( p_dst_matx_cols_read_out_full_n );
    sensitive << ( p_dst_maty_cols_read_out_full_n );
    sensitive << ( tmp_i_i_fu_190_p2 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_i_i_36_fu_214_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage0_subdone );

    start_once_reg = SC_LOGIC_0;
    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "0001";
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_Sobel_Loop_1_proc374_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, start_full_n, "(port)start_full_n");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, start_out, "(port)start_out");
    sc_trace(mVcdFile, start_write, "(port)start_write");
    sc_trace(mVcdFile, p_src_mat_rows_read, "(port)p_src_mat_rows_read");
    sc_trace(mVcdFile, p_src_mat_cols_read, "(port)p_src_mat_cols_read");
    sc_trace(mVcdFile, p_src_mat_data_V_address0, "(port)p_src_mat_data_V_address0");
    sc_trace(mVcdFile, p_src_mat_data_V_ce0, "(port)p_src_mat_data_V_ce0");
    sc_trace(mVcdFile, p_src_mat_data_V_q0, "(port)p_src_mat_data_V_q0");
    sc_trace(mVcdFile, p_src_V_V_din, "(port)p_src_V_V_din");
    sc_trace(mVcdFile, p_src_V_V_full_n, "(port)p_src_V_V_full_n");
    sc_trace(mVcdFile, p_src_V_V_write, "(port)p_src_V_V_write");
    sc_trace(mVcdFile, p_dst_matx_rows_read, "(port)p_dst_matx_rows_read");
    sc_trace(mVcdFile, p_dst_matx_cols_read, "(port)p_dst_matx_cols_read");
    sc_trace(mVcdFile, p_dst_maty_cols_read, "(port)p_dst_maty_cols_read");
    sc_trace(mVcdFile, p_src_mat_rows_read_out_din, "(port)p_src_mat_rows_read_out_din");
    sc_trace(mVcdFile, p_src_mat_rows_read_out_full_n, "(port)p_src_mat_rows_read_out_full_n");
    sc_trace(mVcdFile, p_src_mat_rows_read_out_write, "(port)p_src_mat_rows_read_out_write");
    sc_trace(mVcdFile, p_src_mat_cols_read_out_din, "(port)p_src_mat_cols_read_out_din");
    sc_trace(mVcdFile, p_src_mat_cols_read_out_full_n, "(port)p_src_mat_cols_read_out_full_n");
    sc_trace(mVcdFile, p_src_mat_cols_read_out_write, "(port)p_src_mat_cols_read_out_write");
    sc_trace(mVcdFile, p_dst_matx_rows_read_out_din, "(port)p_dst_matx_rows_read_out_din");
    sc_trace(mVcdFile, p_dst_matx_rows_read_out_full_n, "(port)p_dst_matx_rows_read_out_full_n");
    sc_trace(mVcdFile, p_dst_matx_rows_read_out_write, "(port)p_dst_matx_rows_read_out_write");
    sc_trace(mVcdFile, p_dst_matx_cols_read_out_din, "(port)p_dst_matx_cols_read_out_din");
    sc_trace(mVcdFile, p_dst_matx_cols_read_out_full_n, "(port)p_dst_matx_cols_read_out_full_n");
    sc_trace(mVcdFile, p_dst_matx_cols_read_out_write, "(port)p_dst_matx_cols_read_out_write");
    sc_trace(mVcdFile, p_dst_maty_cols_read_out_din, "(port)p_dst_maty_cols_read_out_din");
    sc_trace(mVcdFile, p_dst_maty_cols_read_out_full_n, "(port)p_dst_maty_cols_read_out_full_n");
    sc_trace(mVcdFile, p_dst_maty_cols_read_out_write, "(port)p_dst_maty_cols_read_out_write");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, real_start, "real_start");
    sc_trace(mVcdFile, start_once_reg, "start_once_reg");
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, internal_ap_ready, "internal_ap_ready");
    sc_trace(mVcdFile, p_src_V_V_blk_n, "p_src_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_i_i_36_reg_264, "tmp_i_i_36_reg_264");
    sc_trace(mVcdFile, p_src_mat_rows_read_out_blk_n, "p_src_mat_rows_read_out_blk_n");
    sc_trace(mVcdFile, p_src_mat_cols_read_out_blk_n, "p_src_mat_cols_read_out_blk_n");
    sc_trace(mVcdFile, p_dst_matx_rows_read_out_blk_n, "p_dst_matx_rows_read_out_blk_n");
    sc_trace(mVcdFile, p_dst_matx_cols_read_out_blk_n, "p_dst_matx_cols_read_out_blk_n");
    sc_trace(mVcdFile, p_dst_maty_cols_read_out_blk_n, "p_dst_maty_cols_read_out_blk_n");
    sc_trace(mVcdFile, j_i_i_reg_167, "j_i_i_reg_167");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, tmp_fu_178_p1, "tmp_fu_178_p1");
    sc_trace(mVcdFile, tmp_reg_245, "tmp_reg_245");
    sc_trace(mVcdFile, tmp_i_i_fu_190_p2, "tmp_i_i_fu_190_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, i_fu_195_p2, "i_fu_195_p2");
    sc_trace(mVcdFile, i_reg_254, "i_reg_254");
    sc_trace(mVcdFile, tmp_21_i_i_fu_201_p2, "tmp_21_i_i_fu_201_p2");
    sc_trace(mVcdFile, tmp_21_i_i_reg_259, "tmp_21_i_i_reg_259");
    sc_trace(mVcdFile, tmp_i_i_36_fu_214_p2, "tmp_i_i_36_fu_214_p2");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage0_iter0, "ap_block_state3_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, j_fu_219_p2, "j_fu_219_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state3, "ap_condition_pp0_exit_iter0_state3");
    sc_trace(mVcdFile, i_i_i_reg_156, "i_i_i_reg_156");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, p_sum1_cast_i_i_fu_230_p1, "p_sum1_cast_i_i_fu_230_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage0_01001, "ap_block_pp0_stage0_01001");
    sc_trace(mVcdFile, i_cast_i_i_fu_182_p1, "i_cast_i_i_fu_182_p1");
    sc_trace(mVcdFile, tmp_13_fu_186_p1, "tmp_13_fu_186_p1");
    sc_trace(mVcdFile, j_cast_i_i_fu_206_p1, "j_cast_i_i_fu_206_p1");
    sc_trace(mVcdFile, tmp_14_fu_210_p1, "tmp_14_fu_210_p1");
    sc_trace(mVcdFile, p_sum1_i_i_fu_225_p2, "p_sum1_i_i_fu_225_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

a0_Sobel_Loop_1_proc374::~a0_Sobel_Loop_1_proc374() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void a0_Sobel_Loop_1_proc374::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                    esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_0))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()) && 
             esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state3.read()))) {
            ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state3.read() ^ ap_const_logic_1);
        } else if (esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read())) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        } else if ((esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_1) && 
                    esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
            ap_enable_reg_pp0_iter1 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_i_i_reg_156 = i_reg_254.read();
    } else if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        i_i_i_reg_156 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && 
         esl_seteq<1,1,1>(ap_const_lv1_1, tmp_i_i_36_fu_214_p2.read()))) {
        j_i_i_reg_167 = j_fu_219_p2.read();
    } else if ((esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_1) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        j_i_i_reg_167 = ap_const_lv31_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        start_once_reg = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()) && 
             esl_seteq<1,1,1>(ap_const_logic_0, internal_ap_ready.read()))) {
            start_once_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, internal_ap_ready.read())) {
            start_once_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_254 = i_fu_195_p2.read();
    }
    if ((esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        tmp_21_i_i_reg_259 = tmp_21_i_i_fu_201_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        tmp_i_i_36_reg_264 = tmp_i_i_36_fu_214_p2.read();
    }
    if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        tmp_reg_245 = tmp_fu_178_p1.read();
    }
}

void a0_Sobel_Loop_1_proc374::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[2];
}

void a0_Sobel_Loop_1_proc374::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void a0_Sobel_Loop_1_proc374::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void a0_Sobel_Loop_1_proc374::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[3];
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_pp0_stage0_01001() {
    ap_block_pp0_stage0_01001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_i_i_36_reg_264.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_full_n.read()));
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_i_i_36_reg_264.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_full_n.read()));
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(tmp_i_i_36_reg_264.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_full_n.read()));
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_state3_pp0_stage0_iter0() {
    ap_block_state3_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_Sobel_Loop_1_proc374::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = (esl_seteq<1,1,1>(tmp_i_i_36_reg_264.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_const_logic_0, p_src_V_V_full_n.read()));
}

void a0_Sobel_Loop_1_proc374::thread_ap_condition_pp0_exit_iter0_state3() {
    if (esl_seteq<1,1,1>(tmp_i_i_36_fu_214_p2.read(), ap_const_lv1_0)) {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state3 = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void a0_Sobel_Loop_1_proc374::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void a0_Sobel_Loop_1_proc374::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_ap_ready() {
    ap_ready = internal_ap_ready.read();
}

void a0_Sobel_Loop_1_proc374::thread_i_cast_i_i_fu_182_p1() {
    i_cast_i_i_fu_182_p1 = esl_zext<32,31>(i_i_i_reg_156.read());
}

void a0_Sobel_Loop_1_proc374::thread_i_fu_195_p2() {
    i_fu_195_p2 = (!ap_const_lv31_1.is_01() || !i_i_i_reg_156.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(i_i_i_reg_156.read()));
}

void a0_Sobel_Loop_1_proc374::thread_internal_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_0))) {
        internal_ap_ready = ap_const_logic_1;
    } else {
        internal_ap_ready = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_j_cast_i_i_fu_206_p1() {
    j_cast_i_i_fu_206_p1 = esl_zext<32,31>(j_i_i_reg_167.read());
}

void a0_Sobel_Loop_1_proc374::thread_j_fu_219_p2() {
    j_fu_219_p2 = (!ap_const_lv31_1.is_01() || !j_i_i_reg_167.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(j_i_i_reg_167.read()));
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_matx_cols_read_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_dst_matx_cols_read_out_blk_n = p_dst_matx_cols_read_out_full_n.read();
    } else {
        p_dst_matx_cols_read_out_blk_n = ap_const_logic_1;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_matx_cols_read_out_din() {
    p_dst_matx_cols_read_out_din = p_dst_matx_cols_read.read();
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_matx_cols_read_out_write() {
    if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_dst_matx_cols_read_out_write = ap_const_logic_1;
    } else {
        p_dst_matx_cols_read_out_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_matx_rows_read_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_dst_matx_rows_read_out_blk_n = p_dst_matx_rows_read_out_full_n.read();
    } else {
        p_dst_matx_rows_read_out_blk_n = ap_const_logic_1;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_matx_rows_read_out_din() {
    p_dst_matx_rows_read_out_din = p_dst_matx_rows_read.read();
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_matx_rows_read_out_write() {
    if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_dst_matx_rows_read_out_write = ap_const_logic_1;
    } else {
        p_dst_matx_rows_read_out_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_maty_cols_read_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_dst_maty_cols_read_out_blk_n = p_dst_maty_cols_read_out_full_n.read();
    } else {
        p_dst_maty_cols_read_out_blk_n = ap_const_logic_1;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_maty_cols_read_out_din() {
    p_dst_maty_cols_read_out_din = p_dst_maty_cols_read.read();
}

void a0_Sobel_Loop_1_proc374::thread_p_dst_maty_cols_read_out_write() {
    if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_dst_maty_cols_read_out_write = ap_const_logic_1;
    } else {
        p_dst_maty_cols_read_out_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(tmp_i_i_36_reg_264.read(), ap_const_lv1_1))) {
        p_src_V_V_blk_n = p_src_V_V_full_n.read();
    } else {
        p_src_V_V_blk_n = ap_const_logic_1;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_V_V_din() {
    p_src_V_V_din = p_src_mat_data_V_q0.read();
}

void a0_Sobel_Loop_1_proc374::thread_p_src_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(tmp_i_i_36_reg_264.read(), ap_const_lv1_1) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        p_src_V_V_write = ap_const_logic_1;
    } else {
        p_src_V_V_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_cols_read_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_src_mat_cols_read_out_blk_n = p_src_mat_cols_read_out_full_n.read();
    } else {
        p_src_mat_cols_read_out_blk_n = ap_const_logic_1;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_cols_read_out_din() {
    p_src_mat_cols_read_out_din = p_src_mat_cols_read.read();
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_cols_read_out_write() {
    if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_src_mat_cols_read_out_write = ap_const_logic_1;
    } else {
        p_src_mat_cols_read_out_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_data_V_address0() {
    p_src_mat_data_V_address0 =  (sc_lv<19>) (p_sum1_cast_i_i_fu_230_p1.read());
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_data_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1))) {
        p_src_mat_data_V_ce0 = ap_const_logic_1;
    } else {
        p_src_mat_data_V_ce0 = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_rows_read_out_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        p_src_mat_rows_read_out_blk_n = p_src_mat_rows_read_out_full_n.read();
    } else {
        p_src_mat_rows_read_out_blk_n = ap_const_logic_1;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_rows_read_out_din() {
    p_src_mat_rows_read_out_din = p_src_mat_rows_read.read();
}

void a0_Sobel_Loop_1_proc374::thread_p_src_mat_rows_read_out_write() {
    if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        p_src_mat_rows_read_out_write = ap_const_logic_1;
    } else {
        p_src_mat_rows_read_out_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_p_sum1_cast_i_i_fu_230_p1() {
    p_sum1_cast_i_i_fu_230_p1 = esl_zext<32,20>(p_sum1_i_i_fu_225_p2.read());
}

void a0_Sobel_Loop_1_proc374::thread_p_sum1_i_i_fu_225_p2() {
    p_sum1_i_i_fu_225_p2 = (!tmp_21_i_i_reg_259.read().is_01() || !tmp_14_fu_210_p1.read().is_01())? sc_lv<20>(): (sc_biguint<20>(tmp_21_i_i_reg_259.read()) + sc_biguint<20>(tmp_14_fu_210_p1.read()));
}

void a0_Sobel_Loop_1_proc374::thread_real_start() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_full_n.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()))) {
        real_start = ap_const_logic_0;
    } else {
        real_start = ap_start.read();
    }
}

void a0_Sobel_Loop_1_proc374::thread_start_out() {
    start_out = real_start.read();
}

void a0_Sobel_Loop_1_proc374::thread_start_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, start_once_reg.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, real_start.read()))) {
        start_write = ap_const_logic_1;
    } else {
        start_write = ap_const_logic_0;
    }
}

void a0_Sobel_Loop_1_proc374::thread_tmp_13_fu_186_p1() {
    tmp_13_fu_186_p1 = i_i_i_reg_156.read().range(20-1, 0);
}

void a0_Sobel_Loop_1_proc374::thread_tmp_14_fu_210_p1() {
    tmp_14_fu_210_p1 = j_i_i_reg_167.read().range(20-1, 0);
}

void a0_Sobel_Loop_1_proc374::thread_tmp_21_i_i_fu_201_p2() {
    tmp_21_i_i_fu_201_p2 = (!tmp_reg_245.read().is_01() || !tmp_13_fu_186_p1.read().is_01())? sc_lv<20>(): sc_bigint<20>(tmp_reg_245.read()) * sc_bigint<20>(tmp_13_fu_186_p1.read());
}

void a0_Sobel_Loop_1_proc374::thread_tmp_fu_178_p1() {
    tmp_fu_178_p1 = p_src_mat_cols_read.read().range(20-1, 0);
}

void a0_Sobel_Loop_1_proc374::thread_tmp_i_i_36_fu_214_p2() {
    tmp_i_i_36_fu_214_p2 = (!j_cast_i_i_fu_206_p1.read().is_01() || !p_src_mat_cols_read.read().is_01())? sc_lv<1>(): (sc_bigint<32>(j_cast_i_i_fu_206_p1.read()) < sc_bigint<32>(p_src_mat_cols_read.read()));
}

void a0_Sobel_Loop_1_proc374::thread_tmp_i_i_fu_190_p2() {
    tmp_i_i_fu_190_p2 = (!i_cast_i_i_fu_182_p1.read().is_01() || !p_src_mat_rows_read.read().is_01())? sc_lv<1>(): (sc_bigint<32>(i_cast_i_i_fu_182_p1.read()) < sc_bigint<32>(p_src_mat_rows_read.read()));
}

void a0_Sobel_Loop_1_proc374::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((!(esl_seteq<1,1,1>(p_dst_maty_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_dst_matx_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_cols_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(p_src_mat_rows_read_out_full_n.read(), ap_const_logic_0) || esl_seteq<1,1,1>(real_start.read(), ap_const_logic_0) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(tmp_i_i_fu_190_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if (!(esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(tmp_i_i_36_fu_214_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_enable_reg_pp0_iter0.read(), ap_const_logic_1) && esl_seteq<1,1,1>(ap_const_boolean_0, ap_block_pp0_stage0_subdone.read()) && esl_seteq<1,1,1>(tmp_i_i_36_fu_214_p2.read(), ap_const_lv1_0))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXX";
            break;
    }
}

}

