// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _a0_Sobel_HH_
#define _a0_Sobel_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "a0_Sobel_Loop_1_proc374.h"
#include "a0_xFSobelFilter3x3.h"
#include "a0_Sobel_Loop_2_proc38.h"
#include "a0_fifo_w8_d2_A.h"
#include "a0_fifo_w32_d2_A.h"
#include "a0_fifo_w32_d3_A.h"
#include "a0_start_for_xFSobelfYi.h"
#include "a0_start_for_Sobel_Lg8j.h"

namespace ap_rtl {

struct a0_Sobel : public sc_module {
    // Port declarations 47
    sc_in< sc_lv<32> > p_src_mat_rows_read;
    sc_in< sc_lv<32> > p_src_mat_cols_read;
    sc_out< sc_lv<19> > p_src_mat_data_V_address0;
    sc_out< sc_logic > p_src_mat_data_V_ce0;
    sc_out< sc_lv<8> > p_src_mat_data_V_d0;
    sc_in< sc_lv<8> > p_src_mat_data_V_q0;
    sc_out< sc_logic > p_src_mat_data_V_we0;
    sc_out< sc_lv<19> > p_src_mat_data_V_address1;
    sc_out< sc_logic > p_src_mat_data_V_ce1;
    sc_out< sc_lv<8> > p_src_mat_data_V_d1;
    sc_in< sc_lv<8> > p_src_mat_data_V_q1;
    sc_out< sc_logic > p_src_mat_data_V_we1;
    sc_in< sc_lv<32> > p_dst_matx_rows_read;
    sc_in< sc_lv<32> > p_dst_matx_cols_read;
    sc_out< sc_lv<19> > p_dst_matx_data_V_address0;
    sc_out< sc_logic > p_dst_matx_data_V_ce0;
    sc_out< sc_lv<8> > p_dst_matx_data_V_d0;
    sc_in< sc_lv<8> > p_dst_matx_data_V_q0;
    sc_out< sc_logic > p_dst_matx_data_V_we0;
    sc_out< sc_lv<19> > p_dst_matx_data_V_address1;
    sc_out< sc_logic > p_dst_matx_data_V_ce1;
    sc_out< sc_lv<8> > p_dst_matx_data_V_d1;
    sc_in< sc_lv<8> > p_dst_matx_data_V_q1;
    sc_out< sc_logic > p_dst_matx_data_V_we1;
    sc_in< sc_lv<32> > p_dst_maty_cols_read;
    sc_out< sc_lv<19> > p_dst_maty_data_V_address0;
    sc_out< sc_logic > p_dst_maty_data_V_ce0;
    sc_out< sc_lv<8> > p_dst_maty_data_V_d0;
    sc_in< sc_lv<8> > p_dst_maty_data_V_q0;
    sc_out< sc_logic > p_dst_maty_data_V_we0;
    sc_out< sc_lv<19> > p_dst_maty_data_V_address1;
    sc_out< sc_logic > p_dst_maty_data_V_ce1;
    sc_out< sc_lv<8> > p_dst_maty_data_V_d1;
    sc_in< sc_lv<8> > p_dst_maty_data_V_q1;
    sc_out< sc_logic > p_dst_maty_data_V_we1;
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > p_src_mat_rows_read_ap_vld;
    sc_in< sc_logic > p_src_mat_cols_read_ap_vld;
    sc_in< sc_logic > p_dst_matx_rows_read_ap_vld;
    sc_in< sc_logic > p_dst_matx_cols_read_ap_vld;
    sc_in< sc_logic > p_dst_maty_cols_read_ap_vld;
    sc_out< sc_logic > ap_done;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_logic > ap_idle;
    sc_in< sc_logic > ap_continue;
    sc_signal< sc_logic > ap_var_for_const0;


    // Module declarations
    a0_Sobel(sc_module_name name);
    SC_HAS_PROCESS(a0_Sobel);

    ~a0_Sobel();

    sc_trace_file* mVcdFile;

    a0_Sobel_Loop_1_proc374* Sobel_Loop_1_proc374_U0;
    a0_xFSobelFilter3x3* xFSobelFilter3x3_U0;
    a0_Sobel_Loop_2_proc38* Sobel_Loop_2_proc38_U0;
    a0_fifo_w8_d2_A* p_src_V_V_U;
    a0_fifo_w32_d2_A* p_src_mat_rows_read_c_U;
    a0_fifo_w32_d2_A* p_src_mat_cols_read_c_U;
    a0_fifo_w32_d3_A* p_dst_matx_rows_read_s_U;
    a0_fifo_w32_d3_A* p_dst_matx_cols_read_s_U;
    a0_fifo_w32_d3_A* p_dst_maty_cols_read_s_U;
    a0_fifo_w8_d2_A* p_dstx_V_V_U;
    a0_fifo_w8_d2_A* p_dsty_V_V_U;
    a0_start_for_xFSobelfYi* start_for_xFSobelfYi_U;
    a0_start_for_Sobel_Lg8j* start_for_Sobel_Lg8j_U;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_ap_start;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_start_full_n;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_ap_done;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_ap_continue;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_ap_idle;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_ap_ready;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_start_out;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_start_write;
    sc_signal< sc_lv<19> > Sobel_Loop_1_proc374_U0_p_src_mat_data_V_address0;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_src_mat_data_V_ce0;
    sc_signal< sc_lv<8> > Sobel_Loop_1_proc374_U0_p_src_V_V_din;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_src_V_V_write;
    sc_signal< sc_lv<32> > Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_din;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_src_mat_rows_read_out_write;
    sc_signal< sc_lv<32> > Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_din;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_src_mat_cols_read_out_write;
    sc_signal< sc_lv<32> > Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_din;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_dst_matx_rows_read_out_write;
    sc_signal< sc_lv<32> > Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_din;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_dst_matx_cols_read_out_write;
    sc_signal< sc_lv<32> > Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_din;
    sc_signal< sc_logic > Sobel_Loop_1_proc374_U0_p_dst_maty_cols_read_out_write;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_ap_start;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_ap_done;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_ap_continue;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_ap_idle;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_ap_ready;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_p_src_mat_V_V_read;
    sc_signal< sc_lv<8> > xFSobelFilter3x3_U0_p_gradx_mat_V_V_din;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_p_gradx_mat_V_V_write;
    sc_signal< sc_lv<8> > xFSobelFilter3x3_U0_p_grady_mat_V_V_din;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_p_grady_mat_V_V_write;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_p_src_mat_rows_read_read;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_p_src_mat_cols_read_read;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_ap_start;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_ap_done;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_ap_continue;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_ap_idle;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_ap_ready;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_matx_rows_read_read;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_matx_cols_read_read;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dstx_V_V_read;
    sc_signal< sc_lv<19> > Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_address0;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_ce0;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_we0;
    sc_signal< sc_lv<8> > Sobel_Loop_2_proc38_U0_p_dst_matx_data_V_d0;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_maty_cols_read_read;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dsty_V_V_read;
    sc_signal< sc_lv<19> > Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_address0;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_ce0;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_we0;
    sc_signal< sc_lv<8> > Sobel_Loop_2_proc38_U0_p_dst_maty_data_V_d0;
    sc_signal< sc_logic > ap_sync_continue;
    sc_signal< sc_logic > p_src_V_V_full_n;
    sc_signal< sc_lv<8> > p_src_V_V_dout;
    sc_signal< sc_logic > p_src_V_V_empty_n;
    sc_signal< sc_logic > p_src_mat_rows_read_c_full_n;
    sc_signal< sc_lv<32> > p_src_mat_rows_read_c_dout;
    sc_signal< sc_logic > p_src_mat_rows_read_c_empty_n;
    sc_signal< sc_logic > p_src_mat_cols_read_c_full_n;
    sc_signal< sc_lv<32> > p_src_mat_cols_read_c_dout;
    sc_signal< sc_logic > p_src_mat_cols_read_c_empty_n;
    sc_signal< sc_logic > p_dst_matx_rows_read_s_full_n;
    sc_signal< sc_lv<32> > p_dst_matx_rows_read_s_dout;
    sc_signal< sc_logic > p_dst_matx_rows_read_s_empty_n;
    sc_signal< sc_logic > p_dst_matx_cols_read_s_full_n;
    sc_signal< sc_lv<32> > p_dst_matx_cols_read_s_dout;
    sc_signal< sc_logic > p_dst_matx_cols_read_s_empty_n;
    sc_signal< sc_logic > p_dst_maty_cols_read_s_full_n;
    sc_signal< sc_lv<32> > p_dst_maty_cols_read_s_dout;
    sc_signal< sc_logic > p_dst_maty_cols_read_s_empty_n;
    sc_signal< sc_logic > p_dstx_V_V_full_n;
    sc_signal< sc_lv<8> > p_dstx_V_V_dout;
    sc_signal< sc_logic > p_dstx_V_V_empty_n;
    sc_signal< sc_logic > p_dsty_V_V_full_n;
    sc_signal< sc_lv<8> > p_dsty_V_V_dout;
    sc_signal< sc_logic > p_dsty_V_V_empty_n;
    sc_signal< sc_logic > ap_sync_done;
    sc_signal< sc_logic > ap_sync_ready;
    sc_signal< sc_lv<1> > start_for_xFSobelFilter3x3_U0_din;
    sc_signal< sc_logic > start_for_xFSobelFilter3x3_U0_full_n;
    sc_signal< sc_lv<1> > start_for_xFSobelFilter3x3_U0_dout;
    sc_signal< sc_logic > start_for_xFSobelFilter3x3_U0_empty_n;
    sc_signal< sc_lv<1> > start_for_Sobel_Loop_2_proc38_U0_din;
    sc_signal< sc_logic > start_for_Sobel_Loop_2_proc38_U0_full_n;
    sc_signal< sc_lv<1> > start_for_Sobel_Loop_2_proc38_U0_dout;
    sc_signal< sc_logic > start_for_Sobel_Loop_2_proc38_U0_empty_n;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_start_full_n;
    sc_signal< sc_logic > xFSobelFilter3x3_U0_start_write;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_start_full_n;
    sc_signal< sc_logic > Sobel_Loop_2_proc38_U0_start_write;
    static const sc_lv<19> ap_const_lv19_0;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<8> ap_const_lv8_0;
    static const sc_logic ap_const_logic_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_Sobel_Loop_1_proc374_U0_ap_continue();
    void thread_Sobel_Loop_1_proc374_U0_ap_start();
    void thread_Sobel_Loop_1_proc374_U0_start_full_n();
    void thread_Sobel_Loop_2_proc38_U0_ap_continue();
    void thread_Sobel_Loop_2_proc38_U0_ap_start();
    void thread_Sobel_Loop_2_proc38_U0_start_full_n();
    void thread_Sobel_Loop_2_proc38_U0_start_write();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_sync_continue();
    void thread_ap_sync_done();
    void thread_ap_sync_ready();
    void thread_p_dst_matx_data_V_address0();
    void thread_p_dst_matx_data_V_address1();
    void thread_p_dst_matx_data_V_ce0();
    void thread_p_dst_matx_data_V_ce1();
    void thread_p_dst_matx_data_V_d0();
    void thread_p_dst_matx_data_V_d1();
    void thread_p_dst_matx_data_V_we0();
    void thread_p_dst_matx_data_V_we1();
    void thread_p_dst_maty_data_V_address0();
    void thread_p_dst_maty_data_V_address1();
    void thread_p_dst_maty_data_V_ce0();
    void thread_p_dst_maty_data_V_ce1();
    void thread_p_dst_maty_data_V_d0();
    void thread_p_dst_maty_data_V_d1();
    void thread_p_dst_maty_data_V_we0();
    void thread_p_dst_maty_data_V_we1();
    void thread_p_src_mat_data_V_address0();
    void thread_p_src_mat_data_V_address1();
    void thread_p_src_mat_data_V_ce0();
    void thread_p_src_mat_data_V_ce1();
    void thread_p_src_mat_data_V_d0();
    void thread_p_src_mat_data_V_d1();
    void thread_p_src_mat_data_V_we0();
    void thread_p_src_mat_data_V_we1();
    void thread_start_for_Sobel_Loop_2_proc38_U0_din();
    void thread_start_for_xFSobelFilter3x3_U0_din();
    void thread_xFSobelFilter3x3_U0_ap_continue();
    void thread_xFSobelFilter3x3_U0_ap_start();
    void thread_xFSobelFilter3x3_U0_start_full_n();
    void thread_xFSobelFilter3x3_U0_start_write();
};

}

using namespace ap_rtl;

#endif
