// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "a0_xFSobel3x3_1_0_0_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic a0_xFSobel3x3_1_0_0_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic a0_xFSobel3x3_1_0_0_s::ap_const_logic_0 = sc_dt::Log_0;
const bool a0_xFSobel3x3_1_0_0_s::ap_const_boolean_1 = true;
const bool a0_xFSobel3x3_1_0_0_s::ap_const_boolean_0 = false;

a0_xFSobel3x3_1_0_0_s::a0_xFSobel3x3_1_0_0_s(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_xFGradientX3x3_0_0_s_fu_72 = new a0_xFGradientX3x3_0_0_s("grp_xFGradientX3x3_0_0_s_fu_72");
    grp_xFGradientX3x3_0_0_s_fu_72->ap_clk(ap_clk);
    grp_xFGradientX3x3_0_0_s_fu_72->ap_rst(ap_rst);
    grp_xFGradientX3x3_0_0_s_fu_72->t0_V(src_buf1_0_V_read);
    grp_xFGradientX3x3_0_0_s_fu_72->t2_V(src_buf1_2_V_read);
    grp_xFGradientX3x3_0_0_s_fu_72->m0_V(src_buf2_0_V_read);
    grp_xFGradientX3x3_0_0_s_fu_72->m2_V(src_buf2_2_V_read);
    grp_xFGradientX3x3_0_0_s_fu_72->b0_V(src_buf3_0_V_read);
    grp_xFGradientX3x3_0_0_s_fu_72->b2_V(src_buf3_2_V_read);
    grp_xFGradientX3x3_0_0_s_fu_72->ap_return(grp_xFGradientX3x3_0_0_s_fu_72_ap_return);
    grp_xFGradientX3x3_0_0_s_fu_72->ap_ce(grp_xFGradientX3x3_0_0_s_fu_72_ap_ce);
    grp_xFGradientY3x3_0_0_s_fu_88 = new a0_xFGradientY3x3_0_0_s("grp_xFGradientY3x3_0_0_s_fu_88");
    grp_xFGradientY3x3_0_0_s_fu_88->ap_clk(ap_clk);
    grp_xFGradientY3x3_0_0_s_fu_88->ap_rst(ap_rst);
    grp_xFGradientY3x3_0_0_s_fu_88->t0_V(src_buf1_0_V_read);
    grp_xFGradientY3x3_0_0_s_fu_88->t1_V(src_buf1_1_V_read);
    grp_xFGradientY3x3_0_0_s_fu_88->t2_V(src_buf1_2_V_read);
    grp_xFGradientY3x3_0_0_s_fu_88->b0_V(src_buf3_0_V_read);
    grp_xFGradientY3x3_0_0_s_fu_88->b1_V(src_buf3_1_V_read);
    grp_xFGradientY3x3_0_0_s_fu_88->b2_V(src_buf3_2_V_read);
    grp_xFGradientY3x3_0_0_s_fu_88->ap_return(grp_xFGradientY3x3_0_0_s_fu_88_ap_return);
    grp_xFGradientY3x3_0_0_s_fu_88->ap_ce(grp_xFGradientY3x3_0_0_s_fu_88_ap_ce);

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_state1_pp0_stage0_iter0_ignore_call8);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter1_ignore_call8);

    SC_METHOD(thread_ap_return_0);
    sensitive << ( grp_xFGradientX3x3_0_0_s_fu_72_ap_return );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_return_1);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );
    sensitive << ( grp_xFGradientY3x3_0_0_s_fu_88_ap_return );

    SC_METHOD(thread_grp_xFGradientX3x3_0_0_s_fu_72_ap_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    SC_METHOD(thread_grp_xFGradientY3x3_0_0_s_fu_88_ap_ce);
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_ce );

    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "a0_xFSobel3x3_1_0_0_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, src_buf1_0_V_read, "(port)src_buf1_0_V_read");
    sc_trace(mVcdFile, src_buf1_1_V_read, "(port)src_buf1_1_V_read");
    sc_trace(mVcdFile, src_buf1_2_V_read, "(port)src_buf1_2_V_read");
    sc_trace(mVcdFile, src_buf2_0_V_read, "(port)src_buf2_0_V_read");
    sc_trace(mVcdFile, src_buf2_2_V_read, "(port)src_buf2_2_V_read");
    sc_trace(mVcdFile, src_buf3_0_V_read, "(port)src_buf3_0_V_read");
    sc_trace(mVcdFile, src_buf3_1_V_read, "(port)src_buf3_1_V_read");
    sc_trace(mVcdFile, src_buf3_2_V_read, "(port)src_buf3_2_V_read");
    sc_trace(mVcdFile, ap_return_0, "(port)ap_return_0");
    sc_trace(mVcdFile, ap_return_1, "(port)ap_return_1");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, grp_xFGradientX3x3_0_0_s_fu_72_ap_return, "grp_xFGradientX3x3_0_0_s_fu_72_ap_return");
    sc_trace(mVcdFile, grp_xFGradientX3x3_0_0_s_fu_72_ap_ce, "grp_xFGradientX3x3_0_0_s_fu_72_ap_ce");
    sc_trace(mVcdFile, ap_block_state1_pp0_stage0_iter0_ignore_call8, "ap_block_state1_pp0_stage0_iter0_ignore_call8");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter1_ignore_call8, "ap_block_state2_pp0_stage0_iter1_ignore_call8");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, grp_xFGradientY3x3_0_0_s_fu_88_ap_return, "grp_xFGradientY3x3_0_0_s_fu_88_ap_return");
    sc_trace(mVcdFile, grp_xFGradientY3x3_0_0_s_fu_88_ap_ce, "grp_xFGradientY3x3_0_0_s_fu_88_ap_ce");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
#endif

    }
}

a0_xFSobel3x3_1_0_0_s::~a0_xFSobel3x3_1_0_0_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete grp_xFGradientX3x3_0_0_s_fu_72;
    delete grp_xFGradientY3x3_0_0_s_fu_88;
}

void a0_xFSobel3x3_1_0_0_s::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_xFSobel3x3_1_0_0_s::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_xFSobel3x3_1_0_0_s::thread_ap_block_state1_pp0_stage0_iter0_ignore_call8() {
    ap_block_state1_pp0_stage0_iter0_ignore_call8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_xFSobel3x3_1_0_0_s::thread_ap_block_state2_pp0_stage0_iter1_ignore_call8() {
    ap_block_state2_pp0_stage0_iter1_ignore_call8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void a0_xFSobel3x3_1_0_0_s::thread_ap_return_0() {
    ap_return_0 = grp_xFGradientX3x3_0_0_s_fu_72_ap_return.read();
}

void a0_xFSobel3x3_1_0_0_s::thread_ap_return_1() {
    ap_return_1 = grp_xFGradientY3x3_0_0_s_fu_88_ap_return.read();
}

void a0_xFSobel3x3_1_0_0_s::thread_grp_xFGradientX3x3_0_0_s_fu_72_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_xFGradientX3x3_0_0_s_fu_72_ap_ce = ap_const_logic_1;
    } else {
        grp_xFGradientX3x3_0_0_s_fu_72_ap_ce = ap_const_logic_0;
    }
}

void a0_xFSobel3x3_1_0_0_s::thread_grp_xFGradientY3x3_0_0_s_fu_88_ap_ce() {
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_ce.read()))) {
        grp_xFGradientY3x3_0_0_s_fu_88_ap_ce = ap_const_logic_1;
    } else {
        grp_xFGradientY3x3_0_0_s_fu_88_ap_ce = ap_const_logic_0;
    }
}

}

