-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.1
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity a0_xFSobel3x3_1_0_0_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    src_buf1_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf1_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf1_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf2_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf2_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf3_0_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf3_1_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    src_buf3_2_V_read : IN STD_LOGIC_VECTOR (7 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    ap_ce : IN STD_LOGIC );
end;


architecture behav of a0_xFSobel3x3_1_0_0_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal grp_xFGradientX3x3_0_0_s_fu_72_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFGradientX3x3_0_0_s_fu_72_ap_ce : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0_ignore_call8 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1_ignore_call8 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal grp_xFGradientY3x3_0_0_s_fu_88_ap_return : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_xFGradientY3x3_0_0_s_fu_88_ap_ce : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;

    component a0_xFGradientX3x3_0_0_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        t0_V : IN STD_LOGIC_VECTOR (7 downto 0);
        t2_V : IN STD_LOGIC_VECTOR (7 downto 0);
        m0_V : IN STD_LOGIC_VECTOR (7 downto 0);
        m2_V : IN STD_LOGIC_VECTOR (7 downto 0);
        b0_V : IN STD_LOGIC_VECTOR (7 downto 0);
        b2_V : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;


    component a0_xFGradientY3x3_0_0_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        t0_V : IN STD_LOGIC_VECTOR (7 downto 0);
        t1_V : IN STD_LOGIC_VECTOR (7 downto 0);
        t2_V : IN STD_LOGIC_VECTOR (7 downto 0);
        b0_V : IN STD_LOGIC_VECTOR (7 downto 0);
        b1_V : IN STD_LOGIC_VECTOR (7 downto 0);
        b2_V : IN STD_LOGIC_VECTOR (7 downto 0);
        ap_return : OUT STD_LOGIC_VECTOR (7 downto 0);
        ap_ce : IN STD_LOGIC );
    end component;



begin
    grp_xFGradientX3x3_0_0_s_fu_72 : component a0_xFGradientX3x3_0_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        t0_V => src_buf1_0_V_read,
        t2_V => src_buf1_2_V_read,
        m0_V => src_buf2_0_V_read,
        m2_V => src_buf2_2_V_read,
        b0_V => src_buf3_0_V_read,
        b2_V => src_buf3_2_V_read,
        ap_return => grp_xFGradientX3x3_0_0_s_fu_72_ap_return,
        ap_ce => grp_xFGradientX3x3_0_0_s_fu_72_ap_ce);

    grp_xFGradientY3x3_0_0_s_fu_88 : component a0_xFGradientY3x3_0_0_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        t0_V => src_buf1_0_V_read,
        t1_V => src_buf1_1_V_read,
        t2_V => src_buf1_2_V_read,
        b0_V => src_buf3_0_V_read,
        b1_V => src_buf3_1_V_read,
        b2_V => src_buf3_2_V_read,
        ap_return => grp_xFGradientY3x3_0_0_s_fu_88_ap_return,
        ap_ce => grp_xFGradientY3x3_0_0_s_fu_88_ap_ce);




        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0_ignore_call8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1_ignore_call8 <= not((ap_const_boolean_1 = ap_const_boolean_1));
    ap_return_0 <= grp_xFGradientX3x3_0_0_s_fu_72_ap_return;
    ap_return_1 <= grp_xFGradientY3x3_0_0_s_fu_88_ap_return;

    grp_xFGradientX3x3_0_0_s_fu_72_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            grp_xFGradientX3x3_0_0_s_fu_72_ap_ce <= ap_const_logic_1;
        else 
            grp_xFGradientX3x3_0_0_s_fu_72_ap_ce <= ap_const_logic_0;
        end if; 
    end process;


    grp_xFGradientY3x3_0_0_s_fu_88_ap_ce_assign_proc : process(ap_block_pp0_stage0_11001, ap_ce)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_ce))) then 
            grp_xFGradientY3x3_0_0_s_fu_88_ap_ce <= ap_const_logic_1;
        else 
            grp_xFGradientY3x3_0_0_s_fu_88_ap_ce <= ap_const_logic_0;
        end if; 
    end process;

end behav;
